3 pytorch中张量的操作（下）

王汝嘉 2022-07-14

pytorch中的数据类型

......

In [229]:
import torch

torch.take（） 拿取

In [230]:
# torch.take(input, index)

In [231]:
src = torch.tensor([[1,2,3],[4,5,6]])
src

tensor([[1, 2, 3],
        [4, 5, 6]])

In [232]:
torch.take(input=src,index=torch.tensor([0,2,5]))

tensor([1, 3, 6])

In [233]:
# take函数是将输入展平 以此来赋予位置信息
# 根据索引来拿出对应的数值就可以了

torch.tile（） 复制

In [234]:
# torch.tile(input, dims)

In [235]:
#单维度复制
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [236]:
a.shape

torch.Size([3])

In [237]:
a = a.tile((2))
a

tensor([1, 2, 3, 1, 2, 3])

In [238]:
a.shape

torch.Size([6])

In [239]:
#多维度复制

In [240]:
b = torch.tensor([[1,2],[3,4]])
b

tensor([[1, 2],
        [3, 4]])

In [241]:
b.shape

torch.Size([2, 2])

In [242]:
b = torch.tile(b,dims=(2,2))
b

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [243]:
b.shape

torch.Size([4, 4])

In [244]:
# 根据以上可总结规律  tile复制函数 原本的shape 和 给定的dim 对应相乘 可以得到复制之后的 shape

In [245]:
c = torch.tensor([[1,2],[3,4]])
c

tensor([[1, 2],
        [3, 4]])

In [246]:
torch.tile(c,dims=(2,1))

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

In [247]:
torch.tile(c,dims=(1,2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [248]:
# 根据上边又可以总结规律
        #仅在第0维上变动数值 其效果是行数增大相应的倍数
        #仅在第1维上变动数值 其效果是列数增大相应的倍数

In [249]:
d = torch.rand([2,3,4,5,6,7])
d.shape

torch.Size([2, 3, 4, 5, 6, 7])

In [250]:
e = torch.tile(d,dims=[2,2])
e.shape

torch.Size([2, 3, 4, 5, 12, 14])

In [251]:
f = torch.tile(d,dims=[1,1,1,2,2])
f.shape

torch.Size([2, 3, 4, 5, 12, 14])

In [252]:
#根据上面 我们发现 dims=[2,2] 和 dims=[1,1,1,2,2，]的效果是一样的 也就是说tile函数在shape和dim不匹配的时候 会自动在前面补1

In [253]:
g = torch.rand([2,3])
g.shape

torch.Size([2, 3])

In [254]:
h = torch.tile(g,dims=[2,2,2,2])
h.shape

torch.Size([2, 2, 4, 6])

In [255]:
g = g.unsqueeze(0)
g.shape

torch.Size([1, 2, 3])

In [256]:
g = g.unsqueeze(0)
g.shape

torch.Size([1, 1, 2, 3])

In [257]:
i = torch.tile(g,dims=[2,2,2,2,])
i.shape

torch.Size([2, 2, 4, 6])

In [258]:
# 根据上面我们可以发现 当shape比dim少的时候 会在shape的前面补1 使用unsqueeze的方法 直至补到二者长度相等

torch.transpose

In [259]:
# torch.transpose(input, dim0, dim1)

In [260]:
# 转置 线性代数里边矩阵的转置

In [261]:
a = torch.randn([2,3])
a.shape

torch.Size([2, 3])

In [262]:
# torch.randn 按照高斯分布来随机取值 
# torch.rand 按照均匀分布来随机取值

In [263]:
b = torch.transpose(a,dim0=0,dim1=1)
b.shape

torch.Size([3, 2])

In [264]:
c = torch.transpose(a,dim0=1,dim1=0)
c.shape

torch.Size([3, 2])

In [265]:
# 根据上面可知，dim0 dim1的选择没有从大到小 或者 从小到大的要求 只要写上要交换的两个维度就可以了

In [266]:
d = torch.randn([2,3])
d

tensor([[ 1.0038,  0.8231, -0.1380],
        [-1.0054, -0.8754,  0.8861]])

In [267]:
d = torch.transpose(d,0,1)
d

tensor([[ 1.0038, -1.0054],
        [ 0.8231, -0.8754],
        [-0.1380,  0.8861]])

In [268]:
# 看一下转置的直观理解，转置前矩阵的第0行 作为 转置后矩阵的第0列
# 转置前矩阵的第1行 作为 转置后矩阵的第1列

torch.unbind

In [269]:
# torch.unbind(input, dim=0) 

In [270]:
# Remove a tensor dimension.

In [271]:
# Returns a tuple of all slices along g given dimension,already without it.

In [272]:
a = torch.rand([3,2])
a

tensor([[0.4608, 0.1728],
        [0.5975, 0.6908],
        [0.6517, 0.8630]])

In [273]:
# 按行拆分
torch.unbind(a,dim=0)

(tensor([0.4608, 0.1728]), tensor([0.5975, 0.6908]), tensor([0.6517, 0.8630]))

In [274]:
# 按列拆分
torch.unbind(a,dim=1)

(tensor([0.4608, 0.5975, 0.6517]), tensor([0.1728, 0.6908, 0.8630]))

In [275]:
b = torch.randn([2,3,4])

In [276]:
torch.unbind(b,dim=0)

(tensor([[-0.0233, -0.1939,  0.2030, -1.4739],
         [ 1.0828, -1.7300,  1.5941,  1.4307],
         [ 0.2101, -1.2282,  0.5801, -0.6352]]),
 tensor([[-0.0922, -0.5681,  2.6273, -0.3455],
         [-0.2412, -0.4151,  0.5270,  0.5611],
         [ 1.7443,  0.2686,  0.5696,  2.1441]]))

In [277]:
torch.unbind(b,dim=1)

(tensor([[-0.0233, -0.1939,  0.2030, -1.4739],
         [-0.0922, -0.5681,  2.6273, -0.3455]]),
 tensor([[ 1.0828, -1.7300,  1.5941,  1.4307],
         [-0.2412, -0.4151,  0.5270,  0.5611]]),
 tensor([[ 0.2101, -1.2282,  0.5801, -0.6352],
         [ 1.7443,  0.2686,  0.5696,  2.1441]]))

In [278]:
torch.unbind(b,dim=2)

(tensor([[-0.0233,  1.0828,  0.2101],
         [-0.0922, -0.2412,  1.7443]]),
 tensor([[-0.1939, -1.7300, -1.2282],
         [-0.5681, -0.4151,  0.2686]]),
 tensor([[0.2030, 1.5941, 0.5801],
         [2.6273, 0.5270, 0.5696]]),
 tensor([[-1.4739,  1.4307, -0.6352],
         [-0.3455,  0.5611,  2.1441]]))

In [279]:
# 根据上面可知，对应的要拆分的维度的值 即为最后拆分出的tuple里边元素的个数

unsqueeze

In [280]:
x = torch.tensor([1,2,3,4])

In [281]:
torch.unsqueeze(x,0)

tensor([[1, 2, 3, 4]])

In [282]:
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

where

In [283]:
# dim=-1 则默认对最后一维进行扩充

torch.where

In [284]:
# torch.where(condition, x, y)

In [285]:
# Return a tensor of elements selected from either x or y, depending on condition.

In [286]:
# 对x进行条件conditions审视和过滤，满足的条件表示过滤成功，则仍为x,不满足条件的，则将x替换成对应位置的y

In [287]:
# y可以是带索引的 也可以只是一个标量

In [288]:
# x,y的形状是一样的
x = torch.randn([3,2])
x

tensor([[-0.5951, -0.9366],
        [ 2.4538,  0.1801],
        [-0.3842, -0.9655]])

In [289]:
y = torch.ones_like(x)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [290]:
c = torch.where(x>0,x,y)
c

tensor([[1.0000, 1.0000],
        [2.4538, 0.1801],
        [1.0000, 1.0000]])

In [291]:
# y只是一个标量

In [292]:
yy = torch.tensor([1,])
yy

tensor([1])

In [293]:
d = torch.where(x>0,x,y)
d

tensor([[1.0000, 1.0000],
        [2.4538, 0.1801],
        [1.0000, 1.0000]])

In [294]:
### 请你测试一下 当x,y的shape不同的时候，还可不可以使用where函数

In [295]:
x = torch.randn(3,3,dtype=torch.double)
x

tensor([[ 0.9967,  0.8005, -1.0338],
        [ 1.3953, -0.1150,  0.4888],
        [ 0.4210,  0.0839,  1.0417]], dtype=torch.float64)

In [296]:
x = torch.where(x>0,x,0)
x

RuntimeError: expected scalar type double but found __int64

In [297]:
# 注意这个问题。x y的数据类型需要是一样的

In [298]:
x = torch.where(x>0,x,0.)
x

tensor([[0.9967, 0.8005, 0.0000],
        [1.3953, 0.0000, 0.4888],
        [0.4210, 0.0839, 1.0417]], dtype=torch.float64)

In [299]:
# 这样就可以了

random seed

超级常用的操作

固定随机种子 让模型保持是用随机的数据进行训练的条件 同时让结果可复现

也就是说 让记录下来取随机的方式 下次取随机的时候 仍然这样取

torch.manual_seed(seed)

In [300]:
# torch.manual_seed(seed)

In [301]:
# Sets the seed for generating random numbers. Returns a torch.Generator object.

In [302]:
# Source code:
def manual_seed(seed) -> torch._C.Generator:
    r"""Sets the seed for generating random numbers. Returns a
    `torch.Generator` object.

    Args:
        seed (int): The desired seed. Value must be within the inclusive range
            `[-0x8000_0000_0000_0000, 0xffff_ffff_ffff_ffff]`. Otherwise, a RuntimeError
            is raised. Negative inputs are remapped to positive values with the formula
            `0xffff_ffff_ffff_ffff + seed`.
    """
    seed = int(seed)
    import torch.cuda

    if not torch.cuda._is_in_bad_fork():
        torch.cuda.manual_seed_all(seed)

    return default_generator.manual_seed(seed)

In [303]:
# 也就说，在调用这个函数的时候，它会自己查看是否有cuda 也就是是否在gpu上运行 若是在gpu上运行了 那么也会固定一个随机种子
# 所以不用担心cpu 还是 gpu 直接使用就好

In [304]:
random_seed = torch.manual_seed(1)

In [305]:
# 这样设置一下，它就自动生效了！

In [306]:
a = torch.randn([3,2])
a

tensor([[ 0.6614,  0.2669],
        [ 0.0617,  0.6213],
        [-0.4519, -0.1661]])

In [307]:
# 从设定随机种子的那个代码开始运行，你会发现a的值就是固定的

In [308]:
# 所以要把随机种子的设定，放在项目的最前面

In [309]:
# 建议每个工程都设定一个随机种子 保证工程结果的可复现

In [310]:
# 同时需要注意的是，numpy之中的随机种子是需要单独用numpy库中的函数进行固定的
# numpy.random.seed(0)

随机数方法

torch.bernoulli

In [311]:
# torch.bernoulli(input, *, generator=None, out=None) 

In [312]:
# Draws binary random numbers (0 or 1) from a Bernoulli distribution.

In [313]:
# 给定概率 根据概率生成0，1

In [314]:
a = torch.empty(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [315]:
a.dtype

torch.float32

In [316]:
# 新的操作 默认返回数据类型为float32的全为0的值

In [317]:
a = torch.empty(3,3).uniform_(0,1)
a

tensor([[0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980],
        [0.9371, 0.6556, 0.3138]])

In [318]:
# .uniform_(0,1) 向对象矩阵中 填充范围从0到1的随机数

In [319]:
torch.bernoulli(a)

tensor([[1., 0., 1.],
        [1., 1., 0.],
        [1., 1., 0.]])

In [320]:
# 一个发现：固定随机种子之后 之前 torch.empty里边的值 会被固定 不再为float32 位的0

torch.normal

In [321]:
# 按正态分布随机取值

In [322]:
# torch.normal(mean, std, *, generator=None, out=None)

In [323]:
# mean 均值 std 方差

In [324]:
# 指定均值的范围 方差的范围 来取值
torch.normal(mean=torch.arange(1.,11.),std=torch.arange(1,0,-0.1))

tensor([2.0579, 2.8658, 3.3148, 4.7925, 4.6758, 4.8949, 7.8452, 7.9988, 9.2760,
        9.8649])

In [325]:
# 指定均值和方差，来根据范围取值
torch.normal(mean=2,std=3,size=(1,3))

tensor([[3.0364, 3.5137, 7.4640]])

In [326]:
### 请你根据官方文档 将其它可能的操作记录在下面

rand

In [327]:
torch.rand([2,3])

tensor([[0.8045, 0.6552, 0.1768],
        [0.8248, 0.8036, 0.9434]])

In [328]:
#[0,1)

rand_like

In [329]:
torch.rand_like(torch.ones([3,2]))

tensor([[0.2197, 0.4177],
        [0.4903, 0.5730],
        [0.1205, 0.1452]])

randint

In [330]:
#torch.randint(low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [331]:
torch.randint(8,size=[1,6])

tensor([[1, 3, 4, 2, 4, 0]])

In [332]:
# 从[0,7]之中随机取值 数据类型是int型的

randint_like

In [333]:
# torch.randint_like(input, low=0, high, \*, dtype=None,
# layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [334]:
torch.randint_like(torch.ones([3,2]),low=1,high=8)

tensor([[6., 7.],
        [6., 7.],
        [2., 7.]])

randn

In [335]:
torch.randn([3,2])

tensor([[-0.1814,  0.0393],
        [ 0.9262, -0.9596],
        [ 0.3518, -0.4039]])

randn_like

In [336]:
torch.randn_like(torch.ones([3,2]))

tensor([[ 1.7584, -0.4145],
        [ 0.8561, -0.4429],
        [ 1.4079, -0.0336]])