In [7]:
import torch
import numpy as np

In [2]:
a=[1,2,3.]
type(a)

list

In [3]:
a=[1,2,3.]
b=torch.tensor(a)
b

tensor([1., 2., 3.])

In [4]:
type(b)

torch.Tensor

In [5]:
b.dtype

torch.float32

In [8]:
np.random.normal(2)

2.586441564041898

In [10]:
np.random.normal((2,3))
a=np.random.normal((2,3))
torch.tensor(a)

tensor([2.8712, 2.6975], dtype=torch.float64)

In [11]:
b=torch.tensor(a)
b

tensor([2.8712, 2.6975], dtype=torch.float64)

In [12]:
c=torch.ones_like(b)
c

tensor([1., 1.], dtype=torch.float64)

In [13]:
c=torch.zeros_like(b)
c

tensor([0., 0.], dtype=torch.float64)

In [14]:
c=torch.rand_like(b)
c

tensor([0.8925, 0.1301], dtype=torch.float64)

In [15]:
torch.rand((2,2))

tensor([[0.0813, 0.3692],
        [0.4574, 0.3990]])

In [16]:
a=torch.rand([2,2])
a

tensor([[0.2416, 0.7374],
        [0.8575, 0.4903]])

In [17]:
a.dtype

torch.float32

In [18]:
a.shape

torch.Size([2, 2])

In [19]:
a.device

device(type='cpu')

In [22]:
torch.is_tensor(a)

True

In [24]:
a=torch.tensor(1.0)
a

tensor(1.)

In [25]:
torch.is_nonzero(a)

True

In [26]:
a=torch.tensor(0)
torch.is_nonzero(a)

False

In [28]:
a=torch.rand([2,2,])
a

tensor([[0.0154, 0.7656],
        [0.5033, 0.0997]])

In [30]:
torch.numel(a)

4

In [31]:
torch.zeros([5,5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [33]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [37]:
#即将被弃用，未来只有arange
torch.range(start=0,end=5)

C:\Users\Superman\AppData\Local\Temp\ipykernel_19200\3156877855.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,end=5)


tensor([0., 1., 2., 3., 4., 5.])

In [38]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [39]:
#2*2全为5的张量
torch.full([2,2],5)

tensor([[5, 5],
        [5, 5]])

In [41]:
a=torch.rand([2,2,])
b=torch.rand([2,3,])

a

tensor([[0.5328, 0.4762],
        [0.1309, 0.7852]])

In [42]:
b

tensor([[0.0281, 0.0847, 0.1101],
        [0.6876, 0.7194, 0.2705]])

In [43]:
#dim=1 横着拼
torch.cat([a,b],dim=1)

tensor([[0.5328, 0.4762, 0.0281, 0.0847, 0.1101],
        [0.1309, 0.7852, 0.6876, 0.7194, 0.2705]])

In [44]:
a=torch.rand([2,2,])
b=torch.rand([3,2,])

In [45]:
a

tensor([[0.9004, 0.1633],
        [0.4051, 0.3546]])

In [46]:
b

tensor([[0.0708, 0.0679],
        [0.1634, 0.7073],
        [0.2767, 0.6196]])

In [47]:
#dim=0 竖着拼
torch.cat([a,b],dim=0)

tensor([[0.9004, 0.1633],
        [0.4051, 0.3546],
        [0.0708, 0.0679],
        [0.1634, 0.7073],
        [0.2767, 0.6196]])