In [2]:
import torch

In [3]:
b=torch.rand([3,2,])

In [4]:
b

tensor([[0.4216, 0.2240],
        [0.4242, 0.3623],
        [0.3125, 0.7414]])

In [5]:
torch.chunk(b,chunks=2)

(tensor([[0.4216, 0.2240],
         [0.4242, 0.3623]]),
 tensor([[0.3125, 0.7414]]))

In [6]:
c,d=torch.chunk(b,chunks=2)

In [7]:
c

tensor([[0.4216, 0.2240],
        [0.4242, 0.3623]])

In [8]:
d

tensor([[0.3125, 0.7414]])

In [9]:
#默认dim=0按行分，dim=1按列分
c,d=torch.chunk(b,chunks=2,dim=1)

In [10]:
c

tensor([[0.4216],
        [0.4242],
        [0.3125]])

In [11]:
d

tensor([[0.2240],
        [0.3623],
        [0.7414]])

In [12]:
a=torch.arange(4.)
torch.reshape(a,(2,2))

tensor([[0., 1.],
        [2., 3.]])

In [13]:
b

tensor([[0.4216, 0.2240],
        [0.4242, 0.3623],
        [0.3125, 0.7414]])

In [14]:
torch.reshape(b,[2,3])

tensor([[0.4216, 0.2240, 0.4242],
        [0.3623, 0.3125, 0.7414]])

In [17]:
torch.reshape(torch.reshape(b,[2,3]),[-1])

tensor([0.4216, 0.2240, 0.4242, 0.3623, 0.3125, 0.7414])

In [19]:
torch.reshape(torch.reshape(torch.reshape(b,[2,3]),[-1]),[2,3])

tensor([[0.4216, 0.2240, 0.4242],
        [0.3623, 0.3125, 0.7414]])

In [20]:
a=torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
torch.split(a,2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [23]:
torch.split(a,[1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [24]:
b

tensor([[0.4216, 0.2240],
        [0.4242, 0.3623],
        [0.3125, 0.7414]])

In [25]:
b.shape

torch.Size([3, 2])

In [26]:
torch.reshape(b,[3,1,2])

tensor([[[0.4216, 0.2240]],

        [[0.4242, 0.3623]],

        [[0.3125, 0.7414]]])

In [27]:
#去除掉纬度为一的
torch.squeeze(torch.reshape(b,[3,1,2]))

tensor([[0.4216, 0.2240],
        [0.4242, 0.3623],
        [0.3125, 0.7414]])

In [28]:
torch.reshape(b,[3,1,2,1,1])

tensor([[[[[0.4216]],

          [[0.2240]]]],



        [[[[0.4242]],

          [[0.3623]]]],



        [[[[0.3125]],

          [[0.7414]]]]])

In [29]:
torch.squeeze(torch.reshape(b,[3,1,2,1,1]),dim=1).shape

torch.Size([3, 2, 1, 1])

In [31]:
torch.squeeze(torch.squeeze(torch.reshape(b,[3,1,2,1,1]),dim=1),dim=2).shape

torch.Size([3, 2, 1])

In [33]:
a=torch.rand([3,2])
a

tensor([[0.7003, 0.6386],
        [0.2598, 0.5260],
        [0.2067, 0.9998]])

In [34]:
#堆叠，与cat不同
torch.stack([a,b])

tensor([[[0.7003, 0.6386],
         [0.2598, 0.5260],
         [0.2067, 0.9998]],

        [[0.4216, 0.2240],
         [0.4242, 0.3623],
         [0.3125, 0.7414]]])

In [35]:
torch.stack([a,b]).shape

torch.Size([2, 3, 2])

In [36]:
torch.stack([a,b],dim=1)

tensor([[[0.7003, 0.6386],
         [0.4216, 0.2240]],

        [[0.2598, 0.5260],
         [0.4242, 0.3623]],

        [[0.2067, 0.9998],
         [0.3125, 0.7414]]])

In [37]:
torch.stack([a,b],dim=1).shape

torch.Size([3, 2, 2])