In [1]:
import torch

In [3]:
a=torch.rand([2,3])
a

tensor([[0.5199, 0.9766, 0.0417],
        [0.9844, 0.2087, 0.5822]])

In [4]:
torch.take(a,torch.tensor([0,2,5]))

tensor([0.5199, 0.0417, 0.5822])

In [6]:
b=torch.rand((4,3))
b

tensor([[0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178]])

In [9]:
b_tiled=torch.tile(b,[2,1])
b_tiled

tensor([[0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178],
        [0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178]])

In [10]:
b_tiled=torch.tile(b,[1,3])
b_tiled

tensor([[0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178]])

In [11]:
b_tiled=torch.tile(b,[2,3])
b_tiled

tensor([[0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178],
        [0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555, 0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201, 0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837, 0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178, 0.8443, 0.2100, 0.2178]])

In [16]:
b

tensor([[0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178]])

In [17]:
b.shape

torch.Size([4, 3])

In [14]:
torch.transpose(b,0,1)

tensor([[0.1466, 0.1792, 0.0043, 0.8443],
        [0.3172, 0.3712, 0.5644, 0.2100],
        [0.9555, 0.8201, 0.9837, 0.2178]])

In [15]:
torch.transpose(b,0,1).shape

torch.Size([3, 4])

In [18]:
b

tensor([[0.1466, 0.3172, 0.9555],
        [0.1792, 0.3712, 0.8201],
        [0.0043, 0.5644, 0.9837],
        [0.8443, 0.2100, 0.2178]])

In [19]:
torch.unbind(b,dim=0)

(tensor([0.1466, 0.3172, 0.9555]),
 tensor([0.1792, 0.3712, 0.8201]),
 tensor([0.0043, 0.5644, 0.9837]),
 tensor([0.8443, 0.2100, 0.2178]))

In [20]:
torch.unbind(b,dim=1)

(tensor([0.1466, 0.1792, 0.0043, 0.8443]),
 tensor([0.3172, 0.3712, 0.5644, 0.2100]),
 tensor([0.9555, 0.8201, 0.9837, 0.2178]))

In [21]:
a=torch.rand((2,3,4))
a

tensor([[[0.8651, 0.6749, 0.9718, 0.0440],
         [0.0319, 0.9957, 0.5012, 0.5699],
         [0.0727, 0.5533, 0.1186, 0.7390]],

        [[0.8723, 0.5741, 0.9053, 0.6186],
         [0.2393, 0.3694, 0.1715, 0.7878],
         [0.0568, 0.6717, 0.0679, 0.2324]]])

In [22]:
torch.unbind(a,dim=0)

(tensor([[0.8651, 0.6749, 0.9718, 0.0440],
         [0.0319, 0.9957, 0.5012, 0.5699],
         [0.0727, 0.5533, 0.1186, 0.7390]]),
 tensor([[0.8723, 0.5741, 0.9053, 0.6186],
         [0.2393, 0.3694, 0.1715, 0.7878],
         [0.0568, 0.6717, 0.0679, 0.2324]]))

In [23]:
torch.unbind(a,dim=1)

(tensor([[0.8651, 0.6749, 0.9718, 0.0440],
         [0.8723, 0.5741, 0.9053, 0.6186]]),
 tensor([[0.0319, 0.9957, 0.5012, 0.5699],
         [0.2393, 0.3694, 0.1715, 0.7878]]),
 tensor([[0.0727, 0.5533, 0.1186, 0.7390],
         [0.0568, 0.6717, 0.0679, 0.2324]]))

In [24]:
a

tensor([[[0.8651, 0.6749, 0.9718, 0.0440],
         [0.0319, 0.9957, 0.5012, 0.5699],
         [0.0727, 0.5533, 0.1186, 0.7390]],

        [[0.8723, 0.5741, 0.9053, 0.6186],
         [0.2393, 0.3694, 0.1715, 0.7878],
         [0.0568, 0.6717, 0.0679, 0.2324]]])

In [25]:
a.shape

torch.Size([2, 3, 4])

In [26]:
torch.unsqueeze(a,dim=0)

tensor([[[[0.8651, 0.6749, 0.9718, 0.0440],
          [0.0319, 0.9957, 0.5012, 0.5699],
          [0.0727, 0.5533, 0.1186, 0.7390]],

         [[0.8723, 0.5741, 0.9053, 0.6186],
          [0.2393, 0.3694, 0.1715, 0.7878],
          [0.0568, 0.6717, 0.0679, 0.2324]]]])

In [27]:
torch.unsqueeze(a,dim=0).shape

torch.Size([1, 2, 3, 4])

In [28]:
torch.unsqueeze(a,dim=1).shape

torch.Size([2, 1, 3, 4])

In [31]:
torch.unsqueeze(a,dim=-1).shape

torch.Size([2, 3, 4, 1])

In [32]:
x=torch.randn(3,2)
y=torch.ones(3,2)

In [34]:
x

tensor([[-2.5871,  0.9681],
        [ 0.8639, -0.7946],
        [-1.2119,  0.7576]])

In [35]:
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
torch.where(x>0,x,y)

tensor([[1.0000, 0.9681],
        [0.8639, 1.0000],
        [1.0000, 0.7576]])