In [1]:
import torch
import numpy as np

In [2]:
src=torch.tensor([[4,3,5],[6,7,8]])

In [3]:
torch.take(src.torch.tensor([0,2,5]))

AttributeError: 'Tensor' object has no attribute 'torch'

In [4]:
torch.take(src,torch.tensor([0,2,5]))
#在index索引角度下会把input看成一维张量

tensor([4, 5, 8])

In [5]:
a=torch.rand([4,3])

In [6]:
a

tensor([[0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018]])

In [7]:
a_tiled=torch.tile(a,[2,1])
#tile函数很重要，表示复制

In [8]:
a_tiled

tensor([[0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018],
        [0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018]])

In [9]:
a_tiled=torch.tile(a,[1,3])

In [10]:
a_tiled

tensor([[0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018]])

In [11]:
a_tiled=torch.tile(a,[2,3])

In [12]:
a_tiled

tensor([[0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018],
        [0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975, 0.6558, 0.5879, 0.5975],
        [0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408, 0.2387, 0.4592, 0.6408],
        [0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622, 0.9801, 0.3924, 0.2622],
        [0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018, 0.7122, 0.0551, 0.6018]])

In [13]:
a.shpe

AttributeError: 'Tensor' object has no attribute 'shpe'

In [14]:
a.shape

torch.Size([4, 3])

In [15]:
torch.transpose(a,0,1)
#transpose函数表示转置

tensor([[0.6558, 0.2387, 0.9801, 0.7122],
        [0.5879, 0.4592, 0.3924, 0.0551],
        [0.5975, 0.6408, 0.2622, 0.6018]])

In [16]:
torch.transpose(a,1,0)

tensor([[0.6558, 0.2387, 0.9801, 0.7122],
        [0.5879, 0.4592, 0.3924, 0.0551],
        [0.5975, 0.6408, 0.2622, 0.6018]])

In [17]:
torch.unbind(a,dim=0)
#移除一个张量的维度

(tensor([0.6558, 0.5879, 0.5975]),
 tensor([0.2387, 0.4592, 0.6408]),
 tensor([0.9801, 0.3924, 0.2622]),
 tensor([0.7122, 0.0551, 0.6018]))

In [18]:
torch.unbind(a,dim=1)

(tensor([0.6558, 0.2387, 0.9801, 0.7122]),
 tensor([0.5879, 0.4592, 0.3924, 0.0551]),
 tensor([0.5975, 0.6408, 0.2622, 0.6018]))

In [19]:
a=torch.rand([2,3,4])

In [20]:
a

tensor([[[0.8026, 0.3760, 0.1735, 0.0959],
         [0.1108, 0.6290, 0.9216, 0.0573],
         [0.8868, 0.9981, 0.2219, 0.3437]],

        [[0.1745, 0.3882, 0.8840, 0.5017],
         [0.7454, 0.9612, 0.3814, 0.9514],
         [0.1164, 0.2655, 0.3132, 0.8007]]])

In [21]:
torch.unbind(a,dim=0)

(tensor([[0.8026, 0.3760, 0.1735, 0.0959],
         [0.1108, 0.6290, 0.9216, 0.0573],
         [0.8868, 0.9981, 0.2219, 0.3437]]),
 tensor([[0.1745, 0.3882, 0.8840, 0.5017],
         [0.7454, 0.9612, 0.3814, 0.9514],
         [0.1164, 0.2655, 0.3132, 0.8007]]))

In [22]:
torch.unbind(a,dim=1)

(tensor([[0.8026, 0.3760, 0.1735, 0.0959],
         [0.1745, 0.3882, 0.8840, 0.5017]]),
 tensor([[0.1108, 0.6290, 0.9216, 0.0573],
         [0.7454, 0.9612, 0.3814, 0.9514]]),
 tensor([[0.8868, 0.9981, 0.2219, 0.3437],
         [0.1164, 0.2655, 0.3132, 0.8007]]))

In [23]:
a.shape

torch.Size([2, 3, 4])

In [24]:
torch.unsqueeze(a,dim=0)

tensor([[[[0.8026, 0.3760, 0.1735, 0.0959],
          [0.1108, 0.6290, 0.9216, 0.0573],
          [0.8868, 0.9981, 0.2219, 0.3437]],

         [[0.1745, 0.3882, 0.8840, 0.5017],
          [0.7454, 0.9612, 0.3814, 0.9514],
          [0.1164, 0.2655, 0.3132, 0.8007]]]])

In [25]:
a.shape

torch.Size([2, 3, 4])

In [26]:
torch.unsqueeze(a,dim=0).shape

torch.Size([1, 2, 3, 4])

In [27]:
torch.unsqueeze(a,dim=1).shape

torch.Size([2, 1, 3, 4])

In [28]:
torch.unsqueeze(a,dim=-1).shape

torch.Size([2, 3, 4, 1])

In [29]:
a=torch.rand([2,2])

In [30]:
a

tensor([[0.9670, 0.8392],
        [0.5464, 0.4876]])

In [31]:
b=torch.zeros_likes(a)

AttributeError: module 'torch' has no attribute 'zeros_likes'

In [32]:
b=torch.zeros_like(a)

In [33]:
b

tensor([[0., 0.],
        [0., 0.]])

In [34]:
torch.where(a>0.5,a,b)
#torch.where(condition,x,y)  判断语句，根据condition判断返回x还是y，成立的话返回x否则是返回y

tensor([[0.9670, 0.8392],
        [0.5464, 0.0000]])

In [35]:
torch.randperm(4)

tensor([3, 2, 1, 0])