In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([[1,2.,3],[4,5,6]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
arr = np.array([1,2])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.linspace(0,9,10).reshape(2,5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [15]:
np.linspace(0,9,6).reshape(2,3)

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

In [16]:
np.logspace(0,9,6,base=np.e).reshape(2,3)

array([[1.00000000e+00, 6.04964746e+00, 3.65982344e+01],
       [2.21406416e+02, 1.33943076e+03, 8.10308393e+03]])

In [17]:
np.log(_)

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

In [19]:
np.random.rand(2,3)

array([[0.33308272, 0.89849811, 0.06674541],
       [0.41153157, 0.9050271 , 0.60673579]])

In [20]:
np.random.rand()

0.6540887569291772

In [23]:
np.random.random((3,2))

array([[0.46603251, 0.35060988],
       [0.29381516, 0.16228531],
       [0.68097706, 0.34124398]])

In [24]:
np.random.uniform(-1,1,(2,3))

array([[ 0.39389312, -0.61732906, -0.04033774],
       [-0.9386345 , -0.24013735,  0.82418332]])

In [27]:
rng=np.random.default_rng(42)
rng

Generator(PCG64) at 0x12A16CF53C0

In [28]:
rng.random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [29]:
rng.standard_normal((2,4))

array([[ 0.1278404 , -0.31624259, -0.01680116, -0.85304393],
       [ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121]])

In [30]:
#指定上下界的均匀分布
rng.uniform(0,1,(2,3))

array([[0.4434142 , 0.22723872, 0.55458479],
       [0.06381726, 0.82763117, 0.6316644 ]])

In [33]:
rng.integers(10,size=2)

array([1, 7], dtype=int64)

In [34]:
rng.integers(0,10,(2,3))

array([[7, 3, 0],
       [9, 4, 8]], dtype=int64)

In [36]:
#高斯分布
rng.normal(0,1,(3,5))

array([[-0.42832782, -0.35213355,  0.53230919,  0.36544406,  0.41273261],
       [ 0.430821  ,  2.1416476 , -0.40641502, -0.51224273, -0.81377273],
       [ 0.61597942,  1.12897229, -0.11394746, -0.84015648, -0.82448122]])

In [3]:
rng = np.random.default_rng(seed=42)
arr = rng.random((3,4))
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [4]:
arr.ndim

2

In [5]:
arr.shape

(3, 4)

In [6]:
arr.size

12

In [7]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [8]:
arr.max()

0.9756223516367559

In [9]:
arr.max(axis=0)

array([0.77395605, 0.97562235, 0.85859792, 0.92676499])

In [10]:
arr.max(axis =1)

array([0.85859792, 0.97562235, 0.92676499])

In [11]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [12]:
np.average(arr)

0.6051555606435642

In [14]:
#按列求平均值
np.average(arr,axis=0)

array([0.33208234, 0.62162891, 0.66351188, 0.80339911])

In [15]:
#按行求平均值
np.average(arr,axis=1)

array([0.69220011, 0.65425093, 0.46901565])

In [18]:
np.sum(arr,axis=0)

array([0.99624703, 1.86488673, 1.99053565, 2.41019732])

In [19]:
#累计求和（按行）
np.cumsum(arr,axis=1)

array([[0.77395605, 1.21283449, 2.07143241, 2.76880044],
       [0.09417735, 1.0697997 , 1.8309394 , 2.61700371],
       [0.12811363, 0.57849957, 0.94929759, 1.87606258]])

In [20]:
#标准差
np.std(arr)

0.28783096517727075

In [21]:
#方差
np.var(arr,axis=1)

array([0.02464271, 0.1114405 , 0.0839356 ])

In [25]:
rng = np.random.default_rng(seed=42)
arr = rng.integers(1,100,(3,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [26]:
#reshape 变成另一个形状
arr.reshape(2,2,3)

array([[[ 9, 77, 65],
        [44, 43, 86]],

       [[ 9, 70, 20],
        [10, 53, 97]]], dtype=int64)

In [27]:
arr.ravel()

array([ 9, 77, 65, 44, 43, 86,  9, 70, 20, 10, 53, 97], dtype=int64)

In [28]:
arr.shape

(3, 4)

In [29]:
#扩展一个维度，必须指定维度
np.expand_dims(arr,1).shape

(3, 1, 4)

In [31]:
expanded = np.expand_dims(arr,axis=(1,3))
expanded.shape

(3, 1, 4, 1)

In [32]:
#去除维度为1的
#可以指定，但指定的维度必须为1
np.squeeze(expanded).shape

(3, 4)

In [33]:
#反序
s = "uevol"
s[::-1]

'loveu'

In [35]:
lis = [1,"1",5.2]
lis[::-1]

[5.2, '1', 1]

In [36]:
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [37]:
#默认进行 行反序
arr[::-1]

array([[20, 10, 53, 97],
       [43, 86,  9, 70],
       [ 9, 77, 65, 44]], dtype=int64)

In [38]:
#行反序
arr[::-1,:]

array([[20, 10, 53, 97],
       [43, 86,  9, 70],
       [ 9, 77, 65, 44]], dtype=int64)

In [39]:
#列反序
arr[:,::-1]

array([[44, 65, 77,  9],
       [70,  9, 86, 43],
       [97, 53, 10, 20]], dtype=int64)

In [40]:
#行列都反序
arr[::-1,::-1]

array([[97, 53, 10, 20],
       [70,  9, 86, 43],
       [44, 65, 77,  9]], dtype=int64)

In [41]:
#转置
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [43]:
arr.T

array([[ 9, 43, 20],
       [77, 86, 10],
       [65,  9, 53],
       [44, 70, 97]], dtype=int64)

In [44]:
#转置，可以指定维度
np.transpose(arr).shape

(4, 3)

In [45]:
np.transpose(arr.reshape(1,1,3,4),axes=(0,2,1,3)).shape

(1, 3, 1, 4)

In [46]:
rng = np.random.default_rng(seed=42)
arr = rng.random((5,4))
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ]])

In [47]:
#索引
arr[0]

array([0.77395605, 0.43887844, 0.85859792, 0.69736803])

In [48]:
arr[0,0]

0.7739560485559633

In [62]:
#取一个范围 实验可知为前开后闭的区间 start:stop:step
arr[1:3]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [51]:
#离散
arr[[1,3]]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872]])

In [57]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ]])

In [56]:
arr[1:3,1]

array([0.97562235, 0.45038594])

In [59]:
arr[[1,3]]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872]])

In [66]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ]])

In [64]:
#也可加入步长 如取第0行到第4行且步长为2 则取出来的如下
arr[0:4:2]

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [65]:
#也可以加入列
arr[0:4:2,0:3:2]

array([[0.77395605, 0.85859792],
       [0.12811363, 0.37079802]])

In [67]:
#第一列的值
arr[...,1]

array([0.43887844, 0.97562235, 0.45038594, 0.82276161, 0.06381726])

In [69]:
#拼接
rng = np.random.default_rng(seed=42)
arr1 = rng.random((2,3))
arr2 = rng.random((2,3))
arr1,arr2

(array([[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235]]),
 array([[0.7611397 , 0.78606431, 0.12811363],
        [0.45038594, 0.37079802, 0.92676499]]))

In [70]:
#默认按列进行连接
np.concatenate((arr1,arr2))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499]])

In [72]:
np.concatenate((arr1,arr2),axis = 1)

array([[0.77395605, 0.43887844, 0.85859792, 0.7611397 , 0.78606431,
        0.12811363],
       [0.69736803, 0.09417735, 0.97562235, 0.45038594, 0.37079802,
        0.92676499]])

In [74]:
#重复
rng = np.random.default_rng(42)
arr = rng.integers(0,10,(3,4))
arr

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]], dtype=int64)

In [75]:
#重复两次
np.repeat(arr,2,axis=0)

array([[0, 7, 6, 4],
       [0, 7, 6, 4],
       [4, 8, 0, 6],
       [4, 8, 0, 6],
       [2, 0, 5, 9],
       [2, 0, 5, 9]], dtype=int64)

In [76]:
#拆分
rng = np.random.default_rng(42)
arr = rng.integers(1,100,(6,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97],
       [73, 76, 72, 78],
       [51, 13, 84, 45],
       [50, 37, 19, 92]], dtype=int64)

In [78]:
np.split(arr,3)

[array([[ 9, 77, 65, 44],
        [43, 86,  9, 70]], dtype=int64),
 array([[20, 10, 53, 97],
        [73, 76, 72, 78]], dtype=int64),
 array([[51, 13, 84, 45],
        [50, 37, 19, 92]], dtype=int64)]

In [82]:
#筛选
rng = np.random.default_rng(42)
arr = rng.integers(1,100,(3,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [83]:
arr > 50

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [84]:
#返回满足条件的索引，因为是两个维度，所以会返回两组结果
np.where(arr > 50)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 1, 3, 2, 3], dtype=int64))

In [85]:
#不满足条件的将会被替换为-1
np.where(arr > 50,arr,-1)

array([[-1, 77, 65, -1],
       [-1, 86, -1, 70],
       [-1, -1, 53, 97]], dtype=int64)

In [86]:
#提取
np.extract(arr > 50, arr)

array([77, 65, 86, 70, 53, 97], dtype=int64)

In [89]:
np.unique(arr)

array([ 9, 10, 20, 43, 44, 53, 65, 70, 77, 86, 97], dtype=int64)

In [91]:
#抽样
#第一个参数是要抽样的集合，如果是一个整数，则表示从0到该值
#第二个参数是样本大小
#第三个参数表示结果是否可以重复
#第四个参数表示出现的概率，长度和第一个参数一样
rng = np.random.default_rng(42)
rng.choice(4,2,replace=False,p=[0.1,0.2,0.3,0.4])

array([3, 2], dtype=int64)

In [92]:
#最值
rng = np.random.default_rng(42)
arr = rng.uniform(1,100,(3,4))
arr

array([[77.62164881, 44.44896554, 86.00119407, 70.03943488],
       [10.32355744, 97.58661281, 76.3528305 , 78.82036622],
       [13.68324963, 45.58820785, 37.7090044 , 92.7497339 ]])

In [93]:
#所有值中最大的index(从第一个开始按行挨个数第五个最大)
np.argmax(arr)

5

In [95]:
#按列（axis=0）每一列中最大的值的位置
np.argmax(arr,axis=0)

array([0, 1, 0, 2], dtype=int64)

In [96]:
arr

array([[77.62164881, 44.44896554, 86.00119407, 70.03943488],
       [10.32355744, 97.58661281, 76.3528305 , 78.82036622],
       [13.68324963, 45.58820785, 37.7090044 , 92.7497339 ]])

In [97]:
#索引  默认axis=1
np.argsort(arr)

array([[1, 3, 0, 2],
       [0, 2, 3, 1],
       [0, 2, 1, 3]], dtype=int64)

In [98]:
np.argsort(arr,axis=1)

array([[1, 3, 0, 2],
       [0, 2, 3, 1],
       [0, 2, 1, 3]], dtype=int64)

In [99]:
np.argsort(arr,axis=0)

array([[1, 0, 2, 0],
       [2, 2, 1, 1],
       [0, 1, 0, 2]], dtype=int64)

In [101]:
rng = np.random.default_rng(42)
arr = rng.integers(1,20,(3,4))
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [102]:
#加减乘除
arr * 2

array([[ 4, 30, 26, 18],
       [18, 34,  4, 28],
       [ 8,  4, 22, 38]], dtype=int64)

In [103]:
#平方
arr ** 2

array([[  4, 225, 169,  81],
       [ 81, 289,   4, 196],
       [ 16,   4, 121, 361]], dtype=int64)

In [105]:
#开方
np.sqrt(arr)

array([[1.41421356, 3.87298335, 3.60555128, 3.        ],
       [3.        , 4.12310563, 1.41421356, 3.74165739],
       [2.        , 1.41421356, 3.31662479, 4.35889894]])

In [106]:
#四舍五入 可以指定保留几位小数
np.round(np.sqrt(arr))

array([[1., 4., 4., 3.],
       [3., 4., 1., 4.],
       [2., 1., 3., 4.]])

In [113]:
np.round(np.sqrt(arr),2)

array([[1.41, 3.87, 3.61, 3.  ],
       [3.  , 4.12, 1.41, 3.74],
       [2.  , 1.41, 3.32, 4.36]])

In [109]:
#取整数部分
np.floor(np.sqrt(arr))

array([[1., 3., 3., 3.],
       [3., 4., 1., 3.],
       [2., 1., 3., 4.]])

In [111]:
#有小数的部分全部当1加入整数
np.ceil(np.sqrt(arr))

array([[2., 4., 4., 3.],
       [3., 5., 2., 4.],
       [2., 2., 4., 5.]])

In [114]:
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [115]:
#模运算 求余
np.mod(arr,3)

array([[2, 0, 1, 0],
       [0, 2, 2, 2],
       [1, 2, 2, 1]], dtype=int64)

In [116]:
arr-5

array([[-3, 10,  8,  4],
       [ 4, 12, -3,  9],
       [-1, -3,  6, 14]], dtype=int64)

In [117]:
np.mod(arr,arr-5)

array([[-1,  5,  5,  1],
       [ 1,  5, -1,  5],
       [ 0, -1,  5,  5]], dtype=int64)

In [120]:
#广播
rng = np.random.default_rng(42)
a = rng.integers(1,100,(3,4))
a

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [121]:
#加的为一行四列
a + [1,2,3,4]

array([[ 10,  79,  68,  48],
       [ 44,  88,  12,  74],
       [ 21,  12,  56, 101]], dtype=int64)

In [127]:
#加的为三行四列
b = a + [[1],[2],[3]]
b

array([[ 10,  78,  66,  45],
       [ 45,  88,  11,  72],
       [ 23,  13,  56, 100]], dtype=int64)

In [125]:
#取余
np.mod(a,b)

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [3]:
#矩阵乘法
rng = np.random.default_rng(42)
a = rng.integers(1,10,(3,2))
b = rng.integers(1,10,(2,4))
c = rng.integers(1,10,(3,3))
a,b,c

(array([[1, 7],
        [6, 4],
        [4, 8]], dtype=int64),
 array([[1, 7, 2, 1],
        [5, 9, 7, 7]], dtype=int64),
 array([[7, 8, 5],
        [2, 8, 5],
        [5, 4, 2]], dtype=int64))

In [130]:
#乘法有多种写法
a.dot(b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [131]:
np.dot(a,b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [132]:
a @ b

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [135]:
a.T

array([[1, 6, 4],
       [7, 4, 8]], dtype=int64)

In [136]:
a

array([[1, 7],
       [6, 4],
       [4, 8]], dtype=int64)

In [133]:
#点积
np.vdot(a,a)

182

In [139]:
#内积
np.inner(a,a)

array([[50, 34, 60],
       [34, 52, 56],
       [60, 56, 80]], dtype=int64)

In [140]:
a.dot(a.T)

array([[50, 34, 60],
       [34, 52, 56],
       [60, 56, 80]], dtype=int64)

In [5]:
# ijk,lkm ->ijlm
np.dot(np.ones((5,2,3)),np.ones((4,3,6))).shape

(5, 2, 4, 6)

In [6]:
#ijk,ikl->ijl
np.matmul(np.ones((5,2,3)),np.ones((4,3,6))).shape

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (5,2,3)->(5,newaxis,newaxis) (4,3,6)->(4,newaxis,newaxis)  and requested shape (2,6)

In [7]:
np.matmul(np.ones((4,2,3)),np.ones((4,3,6))).shape

(4, 2, 6)