In [3]:
import torch
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [68]:
# 切割，chunk()函数
a=torch.rand([3,2])
b,c=torch.chunk(a,chunks=2,)
a

tensor([[0.8365, 0.7553],
        [0.1394, 0.7281],
        [0.1746, 0.5137]])

In [69]:
b

tensor([[0.8365, 0.7553],
        [0.1394, 0.7281]])

In [70]:
c

tensor([[0.1746, 0.5137]])

In [7]:
# dim=  默认：0横1竖
b,c=torch.chunk(a,chunks=2,dim=1)
print(b,"\n",c)

tensor([[0.5143],
        [0.5175],
        [0.0202]]) 
 tensor([[0.1898],
        [0.0920],
        [0.3798]])


In [8]:
#gather(),
# 当dim=0，那么输出的数组i中数字的 行 号就依次等于index内的数字，列为index的列号数。
# 当dim=1，那么输出的数组i中数字的 列 号就依次等于index内的数字，行为index的行号数。
b=torch.tensor([[1,2,3],[4,5,6]]) 
index1=torch.tensor([[0,1,1],[0,1,1]])
print (torch.gather(b,dim=0,index=index1))

tensor([[1, 5, 6],
        [1, 5, 6]])


In [9]:
b=torch.tensor([[1,2,3],[4,5,6]]) 
index1=torch.tensor([[0,1,1],[0,1,1]])
print (torch.gather(b,dim=1,index=index1))

tensor([[1, 2, 2],
        [4, 5, 5]])


In [13]:
#reshape()
a=torch.arange(6.)
torch.reshape(a,(2,3,))

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [44]:
b=torch.tensor([[0,1],[2,3]])
torch.reshape(b,(-1,))

tensor([0, 1, 2, 3])

In [48]:
#torch.tensor.scatter_()   dim=0:按行填充，dim=1:按列填充
src=torch.arange(1,11).reshape((2,5))
index=torch.tensor([[0,1,2,0]])
torch.zeros(3,4,dtype=src.dtype).scatter_(0,index,src)

tensor([[1, 0, 0, 4],
        [0, 2, 0, 0],
        [0, 0, 3, 0]])

In [46]:
#zeros()  
#dim=0:zeros的行数="index的值必须在0到self.size(dim) - 1之间.",列数>=index的列数，
#dim=1:zeros的行数>=index的行数,列数="index的值必须在0到self.size(dim) - 1之间."
src=torch.arange(1,11).reshape((2,5))
index=torch.tensor([[0,1,2],[0,1,4]])
torch.zeros(5,3,dtype=src.dtype).scatter_(0,index,src)

tensor([[6, 0, 0],
        [0, 7, 0],
        [0, 0, 3],
        [0, 0, 0],
        [0, 0, 8]])

In [37]:
index=torch.tensor([[0,1,2],[0,1,4]])
torch.zeros(2,5,dtype=src.dtype).scatter_(1,index,src)

tensor([[1, 2, 3, 0, 0],
        [6, 7, 0, 0, 8]])

In [57]:
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 1., 1.]])

In [58]:
#scatter_add()
#不是进行替换，而是进行加法操作，根据index做一些稀疏的加法，除了替换成加法外，其他的跟scatter一样
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[2., 0., 0., 1., 1.],
        [0., 2., 0., 0., 0.],
        [0., 0., 2., 1., 1.]])

In [59]:
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [73]:
#split   
#split可以指定切割长度，chunk只能均分
a=torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [64]:
torch.split(a,[2,3])

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7],
         [8, 9]]))

In [74]:
torch.split(a,2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [76]:
#squeeze 多维度压缩，将维度中的1去掉
c=torch.arange(9).reshape(3,3)
c

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [80]:
c.reshape(3,1,1,3)

tensor([[[[0, 1, 2]]],


        [[[3, 4, 5]]],


        [[[6, 7, 8]]]])

In [82]:
torch.squeeze(c.reshape(3,1,1,3)).shape

torch.Size([3, 3])

In [79]:
#只挤掉一个维度的1,dim表示第几个维度（从0开始）
c.reshape(3,1,3,1,1)

tensor([[[[[0]],

          [[1]],

          [[2]]]],



        [[[[3]],

          [[4]],

          [[5]]]],



        [[[[6]],

          [[7]],

          [[8]]]]])

In [83]:
torch.squeeze(c.reshape(3,1,3,1,1),dim=1).shape

torch.Size([3, 3, 1, 1])

In [84]:
torch.squeeze(c.reshape(3,1,3,1,),dim=3).shape

torch.Size([3, 1, 3])

In [86]:
#stack 多维度堆叠：所有的张量size要一样，dim表示在哪个维度上堆叠
a=torch.rand([3,4])
a

tensor([[0.5096, 0.8031, 0.0853, 0.6240],
        [0.3282, 0.2978, 0.7467, 0.6282],
        [0.4799, 0.3116, 0.7709, 0.0928]])

In [87]:
b=torch.rand([3,4])
b

tensor([[0.6680, 0.7684, 0.0896, 0.8841],
        [0.1674, 0.4611, 0.2019, 0.0577],
        [0.4103, 0.7543, 0.6209, 0.3158]])

In [88]:
torch.stack([a,b]).shape

torch.Size([2, 3, 4])

In [89]:
torch.stack([a,b],dim=1).shape

torch.Size([3, 2, 4])

In [91]:
#take 将src铺平成一维张量，然后根据index索引选取第几维的数
src=torch.tensor([[4,3,5],[6,7,8]])
index=torch.tensor([0,2,5])
torch.take(src,index)

tensor([4, 5, 8])

In [92]:
#tile 复制
x=torch.rand([1,3])
x.tile(2)

tensor([[0.1805, 0.8037, 0.5175, 0.1805, 0.8037, 0.5175]])

In [97]:
y=torch.tensor([[4,3],[2,6]])
torch.tile(y,(3,2)) #行复制3倍，列复制2倍

tensor([[4, 3, 4, 3],
        [2, 6, 2, 6],
        [4, 3, 4, 3],
        [2, 6, 2, 6],
        [4, 3, 4, 3],
        [2, 6, 2, 6]])

In [98]:
#transpose 转置  dim表示要转置的维度
a=torch.rand([3,4])
a

tensor([[0.3644, 0.4968, 0.7499, 0.8928],
        [0.7141, 0.8968, 0.9250, 0.1557],
        [0.9373, 0.6698, 0.3507, 0.1087]])

In [100]:
torch.transpose(a,0,1).shape

torch.Size([4, 3])

In [114]:
#unbind 移除张量的维度:将大张量拆分成小张量，且每个小张量的维度都比大张量的维度降1
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
torch.unbind(torch.tensor([[1,2,3],[4,5,6],[7,8,9]]),dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [110]:
torch.unbind(torch.tensor([[1,2,3],[4,5,6],[7,8,9]]),dim=1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

In [148]:
q=torch.rand((2,3,4))
q

tensor([[[0.7564, 0.1844, 0.2866, 0.8204],
         [0.9386, 0.4221, 0.5172, 0.3612],
         [0.6737, 0.1278, 0.8315, 0.4669]],

        [[0.7644, 0.1073, 0.2571, 0.2013],
         [0.6602, 0.3798, 0.1003, 0.7003],
         [0.1284, 0.5741, 0.2511, 0.9504]]])

In [133]:
torch.unbind(q,dim=1)

(tensor([[0.9626, 0.4239, 0.3124, 0.0665],
         [0.3753, 0.4910, 0.0781, 0.1331]]),
 tensor([[0.5361, 0.9401, 0.5062, 0.6866],
         [0.3693, 0.2283, 0.2502, 0.0085]]),
 tensor([[0.8851, 0.7678, 0.2020, 0.5062],
         [0.4120, 0.9968, 0.2250, 0.7343]]))

In [139]:
#unsqueeze 新增维度
x=torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [140]:
torch.tensor([1,2,3,4]).shape

torch.Size([4])

In [141]:
y=torch.unsqueeze(x,0)
y

tensor([[1, 2, 3, 4]])

In [143]:
torch.unsqueeze(x,0).shape

torch.Size([1, 4])

In [147]:
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [146]:
torch.unsqueeze(x,1).shape

torch.Size([4, 1])

In [149]:
q.shape

torch.Size([2, 3, 4])

In [150]:
#dim=-1表示在最后一个维度增加
torch.unsqueeze(q,-1).shape

torch.Size([2, 3, 4, 1])

In [160]:
#where 判断语句：如果条件成立则返回x，不成立则返回y
x=torch.randn([3,2])
x

tensor([[ 0.7325, -0.6426],
        [-1.7666, -0.6558],
        [-0.4979, -0.3533]])

In [158]:
y=torch.ones(3,2)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [161]:
torch.where(x>0,x,y)

tensor([[0.7325, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000]])