In [2]:
import torch
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [6]:
# 切割，chunk()函数
a=torch.rand([3,2])
b,c=torch.chunk(a,chunks=2,)
print(b)
print(c)

tensor([[0.5143, 0.1898],
        [0.5175, 0.0920]])
tensor([[0.0202, 0.3798]])


In [7]:
# dim=  默认：0横1竖
b,c=torch.chunk(a,chunks=2,dim=1)
print(b,"\n",c)

tensor([[0.5143],
        [0.5175],
        [0.0202]]) 
 tensor([[0.1898],
        [0.0920],
        [0.3798]])


In [8]:
#gather(),
# 当dim=0，那么输出的数组i中数字的 行 号就依次等于index内的数字，列为index的列号数。
# 当dim=1，那么输出的数组i中数字的 列 号就依次等于index内的数字，行为index的行号数。
b=torch.tensor([[1,2,3],[4,5,6]]) 
index1=torch.tensor([[0,1,1],[0,1,1]])
print (torch.gather(b,dim=0,index=index1))

tensor([[1, 5, 6],
        [1, 5, 6]])


In [9]:
b=torch.tensor([[1,2,3],[4,5,6]]) 
index1=torch.tensor([[0,1,1],[0,1,1]])
print (torch.gather(b,dim=1,index=index1))

tensor([[1, 2, 2],
        [4, 5, 5]])
