上：（部分API不太清晰，多看下视频笔记和例子）

1、chunk（dim默认0横1竖）

2、gather、reshape、scatter、split、squeeze 把大小为1的维度移除、stack

下：

1、Pytorch的数据类型

2、take，把任意张量设置成一维张量后取值

3、tile，复制

In [2]:
import torch
a=torch.rand((4,3))
a_tile=torch.tile(a,[2,1])#对行进行复制
a_tile

tensor([[9.4096e-01, 9.4374e-02, 7.7455e-01],
        [1.1728e-01, 7.8546e-01, 8.6875e-01],
        [3.3717e-01, 9.9629e-01, 3.9315e-04],
        [9.9619e-01, 4.4177e-01, 9.7885e-01],
        [9.4096e-01, 9.4374e-02, 7.7455e-01],
        [1.1728e-01, 7.8546e-01, 8.6875e-01],
        [3.3717e-01, 9.9629e-01, 3.9315e-04],
        [9.9619e-01, 4.4177e-01, 9.7885e-01]])

In [3]:
import torch
a=torch.rand((4,3))
a_tile=torch.tile(a,[1,3])#对列进行复制
a_tile

tensor([[0.6243, 0.0889, 0.5484, 0.6243, 0.0889, 0.5484, 0.6243, 0.0889, 0.5484],
        [0.2460, 0.8037, 0.9424, 0.2460, 0.8037, 0.9424, 0.2460, 0.8037, 0.9424],
        [0.1976, 0.5052, 0.4654, 0.1976, 0.5052, 0.4654, 0.1976, 0.5052, 0.4654],
        [0.0278, 0.5154, 0.0727, 0.0278, 0.5154, 0.0727, 0.0278, 0.5154, 0.0727]])

4、transpose，转置

In [6]:
x = torch.randn(2, 3)
x

tensor([[-0.3589, -0.1570,  0.6128],
        [ 0.3115, -0.7713, -0.3530]])

In [7]:
torch.transpose(x, 0, 1)

tensor([[-0.3589,  0.3115],
        [-0.1570, -0.7713],
        [ 0.6128, -0.3530]])

5、unbind，移除张量维度

In [12]:
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]),dim=1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

6、unsqueeze，在指定的维度上扩充一维

In [13]:
a=torch.rand((4,3))
a.shape

torch.Size([4, 3])

In [14]:
torch.unsqueeze(a,dim=0).shape

torch.Size([1, 4, 3])

In [15]:
torch.unsqueeze(a,dim=1).shape

torch.Size([4, 1, 3])

7、where，判断语句

In [16]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
torch.where(x > 0, x, y)

tensor([[1.6773, 0.0831],
        [0.9279, 0.5246],
        [1.0000, 2.8272]])

8、torch.manual_seed(seed)，为生成随机数设置一个种子

9、随机函数
  bernoulli，伯努利采样

In [17]:
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
a

tensor([[0.3204, 0.4158, 0.5688],
        [0.4006, 0.1958, 0.7799],
        [0.2802, 0.0779, 0.7856]])

In [18]:
torch.bernoulli(a) #表概率，只返回0和1

tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

10、normal，高斯分布

11、rand，在[0,1)中采样；

  randint，随机生成整数，需传入上界和下界以及size；

  randn，基于均值为0，标准差为1的正态分布中得到随机数；

  randperm，得到一个随机组合。

In [20]:
torch.randperm(4) #对0、1、2、3进行随机组合，可用于构建数据集

tensor([3, 0, 2, 1])