In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
import forch

ModuleNotFoundError: No module named 'forch'

# 

In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [1]:
import torch

In [2]:
b=torch.rand([3,2])

In [3]:
b

tensor([[0.4091, 0.9253],
        [0.0798, 0.9336],
        [0.1050, 0.9592]])

In [4]:
torch.chunk

<function torch._VariableFunctionsClass.chunk>

In [8]:
torch.chunk(b,chunks=2)

(tensor([[0.4091, 0.9253],
         [0.0798, 0.9336]]),
 tensor([[0.1050, 0.9592]]))

In [ ]:
c,d=torch.chunk(b,chunks=2)
#chunk将一个张量分割成特定数目的张量，如果张量的维度不能被整除,最后的张量会比较小

In [10]:
c

tensor([[0.4091, 0.9253],
        [0.0798, 0.9336]])

In [11]:
d

tensor([[0.1050, 0.9592]])

In [4]:
import torch

In [6]:
b=torch.rand([3,2])

In [7]:
b

tensor([[0.9522, 0.7219],
        [0.1362, 0.0361],
        [0.7649, 0.5464]])

In [8]:
c,d=torch.chunk(b,chunks=2,dim=1)
#dim 默认的0横，1竖

In [9]:
c

tensor([[0.9522],
        [0.1362],
        [0.7649]])

In [10]:
d

tensor([[0.7219],
        [0.0361],
        [0.5464]])

In [11]:
a=torch.arrage(4.)

AttributeError: module 'torch' has no attribute 'arrage'

In [12]:
a=torch.arange(4.)

In [13]:
torch.reshape(a,(2,2))
#reshape能够得到具有相同数据的张量和相同元素的张量,参数是input和shape

tensor([[0., 1.],
        [2., 3.]])

In [14]:
b=torch.tensor([0,1],[2,3])

TypeError: tensor() takes 1 positional argument but 2 were given

In [15]:
b=torch.tensor([[0,1],[2,3]])

In [16]:
torch.reshape(b,(-1,))

tensor([0, 1, 2, 3])

In [17]:
torch.reshape(torch.reshape(b,(-1,),[2,2])

SyntaxError: unexpected EOF while parsing (504455903.py, line 1)

In [18]:
torch.reshape(torch.reshape(b,(-1,)),[2,2])

tensor([[0, 1],
        [2, 3]])

In [19]:
b.shape

torch.Size([2, 2])

In [20]:
torch.reshape(b,[2,1,2])

tensor([[[0, 1]],

        [[2, 3]]])

In [21]:
torch.squeeze(torch.reshape(b,[2,1,2]))
#squeeze 将所有维度为1的input移除掉

tensor([[0, 1],
        [2, 3]])

In [3]:
import torch

In [4]:
b=torch.rand([3,2])

In [6]:
b

tensor([[0.6889, 0.5605],
        [0.2064, 0.7219],
        [0.5528, 0.1837]])

In [7]:
a=torch.rand([3,2])

In [8]:
a

tensor([[0.6152, 0.8115],
        [0.6742, 0.2683],
        [0.9811, 0.8075]])

In [9]:
torch.stack([a,b]).shape

torch.Size([2, 3, 2])

In [10]:
torch.stack([a,b],dim=1)

tensor([[[0.6152, 0.8115],
         [0.6889, 0.5605]],

        [[0.6742, 0.2683],
         [0.2064, 0.7219]],

        [[0.9811, 0.8075],
         [0.5528, 0.1837]]])

In [11]:
torch.stack([a,b],dim=1).shape

torch.Size([3, 2, 2])