2 pytorch张量运算的api

王汝嘉 2022-07-13

索引 切片 聚合 旋转

indexing slicing joining mutating

In [2]:
import torch

In [3]:
# cat

In [4]:
a = torch.full((2,3),2)
a

tensor([[2, 2, 2],
        [2, 2, 2]])

In [5]:
b = torch.full((2,2),3)
b

tensor([[3, 3],
        [3, 3]])

In [6]:
torch.cat((a,b),dim=1)

tensor([[2, 2, 2, 3, 3],
        [2, 2, 2, 3, 3]])

In [7]:
# chunk
#torch.chunk(input, chunks, dim=0)

In [8]:
a = torch.rand([3,2])
a

tensor([[0.7255, 0.0894],
        [0.5402, 0.7757],
        [0.5016, 0.4700]])

In [9]:
# chunks的数目代表的是要切分成的块儿的数目

In [10]:
# 按行切分 
torch.chunk(a,chunks=2,dim=0)

(tensor([[0.7255, 0.0894],
         [0.5402, 0.7757]]),
 tensor([[0.5016, 0.4700]]))

In [11]:
# 按列切分
torch.chunk(a,chunks=2,dim=1)

(tensor([[0.7255],
         [0.5402],
         [0.5016]]),
 tensor([[0.0894],
         [0.7757],
         [0.4700]]))

In [12]:
b,c = torch.chunk(a,chunks=2,dim=0)

In [13]:
b

tensor([[0.7255, 0.0894],
        [0.5402, 0.7757]])

In [14]:
c

tensor([[0.5016, 0.4700]])

In [15]:
#因为被切分的a一共就有三行，所以切分出来的就只有一行

gather  按照索引来提取

In [16]:
#torch.gather(input, dim, index, *, sparse_grad=False, out=None)
# dimension 维度
# dim=0 行
# dim=1 列

In [17]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,2],[3,4]])

In [22]:
a,b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [39]:
# dim=1 维度指的是列
torch.gather(input=a, dim=1, index=torch.tensor([[0, 1], [1, 0]]))
# 第一行的第0个
# 第一行的第1个
# 第二行的第1个
# 第二行的第0个

# 位置信息 [0[0,1],1[0,1]]

# 索引信息 [0[0,1],1[1,0]]


tensor([[1, 2],
        [4, 3]])

In [23]:
b

tensor([[1, 2],
        [3, 4]])

In [41]:
# dim=0 行
torch.gather(b, 0, torch.tensor([[0, 1], [1, 0]]))
# 第一列的第0个
# 第二列的第1个
# 第二列的第1个
# 第二列的第0个

# 位置信息 [0[0,1],1[0,1]]

# 索引信息 [0[0,1],1[1,0]]


tensor([[1, 4],
        [3, 2]])

In [42]:
###这个好奇怪呀

reshape

In [43]:
# torch.reshape(input, shape)

In [44]:
# reshape只改变被改变者的维度 不改变被改变者中包含的数据 和 被改变者中数据的顺序
# 张量之间的变换

In [45]:
a = torch.arange(4.)
a

tensor([0., 1., 2., 3.])

In [47]:
torch.reshape(input=a,shape=(2,2))

tensor([[0., 1.],
        [2., 3.]])

In [52]:
# 注意，顺序是没有进行变化的

In [53]:
# 积累一个小技巧 将shape设置为-1， 就可以将张量改变成一维张量

In [54]:
torch.reshape(a,(-1,))

tensor([0., 1., 2., 3.])

In [55]:
#注意 下面的写法是不对的

In [56]:
torch.reshape(a,-1)

TypeError: reshape(): argument 'shape' (position 2) must be tuple of ints, not int

In [57]:
torch.reshape(a,(-1))

TypeError: reshape(): argument 'shape' (position 2) must be tuple of ints, not int

In [58]:
torch.reshape(a,(-1,)) #这样才是对的

tensor([0., 1., 2., 3.])

In [59]:
b = torch.rand([2,3])
b

tensor([[0.8120, 0.8285, 0.5975],
        [0.8720, 0.0761, 0.2930]])

In [61]:
b=torch.reshape(b,(3,2))
b

tensor([[0.8120, 0.8285],
        [0.5975, 0.8720],
        [0.0761, 0.2930]])

In [62]:
b = torch.reshape(torch.reshape(b,(3,2)),(-1,))
b

tensor([0.8120, 0.8285, 0.5975, 0.8720, 0.0761, 0.2930])

In [63]:
### 请你用连续嵌套的方式 在上边的语句之中再嵌套一层 让b变为它原来的样子[2,3]

scatter

In [66]:
# torch.scatter 是 torch.scatter_ 的out of place的版本

In [69]:
# out-of-place是出位操作
# in-of-place是原位操作  加下划线的一般是原位操作

#位：数据储存在内存之中的位置

In [70]:
#Tensor.scatter_(dim, index, src, reduce=None) 

In [ ]:
#根据index 将src 中的值 填充到对象矩阵之中

In [25]:
src = torch.arange(1,11).reshape(2,5)
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [40]:
index = torch.tensor([[0,1,2,1]])


# 位置信息 [0,1,2,3] 从src之中取得值

# 位置信息 [0,1,2]  行数
# 索引信息 [0,1,2,1] 确定行数之后，再确定所在的列数   向目标矩阵之中填数的位置  

In [41]:
torch.zeros(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [42]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 4, 0],
        [0, 0, 3, 0, 0]])

In [33]:
### 为什么会有一个4呢？

In [95]:
# 索引所在的顺序 代表了从src中的取值 比如index中0就在src中取第0位置的数 也就是取1
# dim=0 表示按行进行选取 索引上各元素的位置和其代表的值共同组成被操作的对象中的位置 
# 比如 索引第0位置的值为0 也就是要将该索引从src中取的值1 替换成被操作对象的（0，0）位置

In [97]:
#因为被操作对象的行数仅为3 所以索引的具体数值范围也就是0-2 排完之后继续到下一块儿进行排列

scatter_add

In [98]:
#不是进行替换 而是进行加法操作 根据index做一些稀疏的加法

In [100]:
torch.ones(3,5,dtype=src.dtype).scatter_add(0,index,src)

tensor([[2, 1, 1, 1, 1],
        [1, 3, 1, 5, 1],
        [1, 1, 4, 1, 1]])

In [101]:
# 除了由替换变成加法之外  其余的操作都是和scatter一样的

split

In [102]:
# 切分的函数  chunk的进化版
# torch.split(tensor, split_size_or_sections, dim=0)

In [103]:
#传入整型数字 size

In [105]:
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [106]:
torch.split(a,split_size_or_sections=2,dim=0)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [109]:
torch.split(a,split_size_or_sections=1,dim=1)

(tensor([[0],
         [2],
         [4],
         [6],
         [8]]),
 tensor([[1],
         [3],
         [5],
         [7],
         [9]]))

In [110]:
torch.split(a,split_size_or_sections=2,dim=1)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),)

In [111]:
# 注意 split函数中split_size_or_sections表示的是切分的尺寸
# chunk函数中 chunks表示的是切分后的结果 切分后的块儿数

In [112]:
# 输入列表list sections

In [113]:
torch.split(a,[1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [117]:
torch.split(a,[2,3])

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7],
         [8, 9]]))

In [121]:
torch.split(a,[1,1],dim=1)

(tensor([[0],
         [2],
         [4],
         [6],
         [8]]),
 tensor([[1],
         [3],
         [5],
         [7],
         [9]]))

In [122]:
# 以后建议大家直接使用split函数 减少chunk函数的使用

In [123]:
### 请你总结一下split函数 比 chunk函数多了哪些功能？

squeeze

In [124]:
# 挤压函数 会将被处理对象的维度值为1的所有维度删掉

In [ ]:
# torch.squeeze(input, dim=None, *, out=None)

In [128]:
a = torch.arange(12).reshape(1,2,1,2,1,3)
a.shape

torch.Size([1, 2, 1, 2, 1, 3])

In [130]:
torch.squeeze(a).shape

torch.Size([2, 2, 3])

In [131]:
#也就是说默认对所有维度值为一的值进行压缩

In [133]:
torch.squeeze(a,dim=0).shape

torch.Size([2, 1, 2, 1, 3])

In [134]:
#使用dim来对张量进行指定位置的压缩

In [135]:
### 请你将张量a的形状变为[2,2,1,3]

unsqueeze

In [139]:
#反挤压 扩充

In [ ]:
# 利用dim来指定要在哪一个维度进行扩充

In [136]:
torch.unsqueeze(torch.squeeze(a,dim=0),dim=0).shape

torch.Size([1, 2, 1, 2, 1, 3])

In [142]:
torch.unsqueeze(torch.squeeze(a,dim=2),dim=2).shape

torch.Size([1, 2, 1, 2, 1, 3])

In [146]:
torch.unsqueeze(torch.squeeze(a,dim=2),dim=3).shape

torch.Size([1, 2, 2, 1, 1, 3])

In [147]:
torch.unsqueeze(torch.squeeze(a,dim=2),dim=1).shape

torch.Size([1, 1, 2, 2, 1, 3])

In [148]:
# 也就说 dim等于 则扩张的效果就会出现第几个维度 并且原来在那个维度的数值是会向后退的

In [149]:
# squeeze是一个重要的函数 会在卷积层 tensformer的自注意力层 和全连接层相连的时候 用到
#通常是将维度压缩到某一个维度 比如通过reshape将张量的高宽结合起来 留出一个1来 通过squeeze函数删掉1

In [150]:
# 举个例子

pytorch中计算机视觉中所用的张量的维度一般是四维 [batch_size,channel,height,width]

In [168]:
a = torch.rand([5,2,26,26])
a

tensor([[[[0.9509, 0.2255, 0.9164,  ..., 0.9829, 0.1996, 0.3726],
          [0.5382, 0.3207, 0.3165,  ..., 0.2100, 0.0707, 0.7517],
          [0.2238, 0.8219, 0.0790,  ..., 0.6543, 0.5695, 0.9315],
          ...,
          [0.9220, 0.9994, 0.7032,  ..., 0.5577, 0.9038, 0.8827],
          [0.9910, 0.2783, 0.9545,  ..., 0.4067, 0.7559, 0.3174],
          [0.1874, 0.1660, 0.6847,  ..., 0.1159, 0.0621, 0.1020]],

         [[0.2972, 0.9987, 0.8191,  ..., 0.5754, 0.1184, 0.9957],
          [0.2713, 0.1085, 0.1615,  ..., 0.2431, 0.0816, 0.2283],
          [0.0309, 0.7513, 0.2476,  ..., 0.1828, 0.6963, 0.3388],
          ...,
          [0.7051, 0.7016, 0.2550,  ..., 0.7210, 0.1507, 0.4064],
          [0.1057, 0.4031, 0.1302,  ..., 0.0321, 0.6980, 0.5367],
          [0.3823, 0.8565, 0.1195,  ..., 0.7493, 0.0418, 0.6106]]],


        [[[0.8937, 0.0122, 0.4450,  ..., 0.6458, 0.1992, 0.3931],
          [0.5224, 0.1936, 0.6414,  ..., 0.5271, 0.6532, 0.3669],
          [0.7672, 0.3211, 0.8265,  ...,

In [169]:
# 假设这个a就是最后卷积层输出的结果

全连接层所要求的特征向量的维度 是两维的 [input_channel,output_channel]

In [170]:
# 我们现在要将这个卷积层出来的结果和全连接层相连 那么我们就要将四维的张量压缩成两维
#通常的压缩手法是 batch_size*channel height*width

In [171]:
a = a.reshape([-1,1,26,26]) #压缩前两维度

In [172]:
a.shape

torch.Size([10, 1, 26, 26])

In [175]:
a = a.reshape([10,1,1,-1])

In [176]:
a.shape

torch.Size([10, 1, 1, 676])

In [177]:
a = a.squeeze()

In [178]:
a.shape

torch.Size([10, 676])

In [179]:
# ok!!!

stack

In [181]:
# torch.stack()
# 扩张维度的拼接   cat是直接拼接 不用扩张维度
# 所有要拼接的张量的形状必须都是一样的

In [ ]:
# torch.stack(tensors, dim=0, *, out=None)

In [185]:
a = torch.rand([3,2])

In [186]:
b = torch.rand([3,2])

In [189]:
c = torch.stack((a,b),dim=0)
c

tensor([[[0.7582, 0.1722],
         [0.4379, 0.5665],
         [0.7714, 0.9877]],

        [[0.7108, 0.9648],
         [0.9730, 0.6206],
         [0.1857, 0.0716]]])

In [190]:
c.shape

torch.Size([2, 3, 2])

In [191]:
d = torch.stack((a,b),dim=1)
d

tensor([[[0.7582, 0.1722],
         [0.7108, 0.9648]],

        [[0.4379, 0.5665],
         [0.9730, 0.6206]],

        [[0.7714, 0.9877],
         [0.1857, 0.0716]]])

In [192]:
d.shape

torch.Size([3, 2, 2])

In [193]:
# 一个规律 取出张量的第1个位置的值
# dim=0 将其加在张量的前面
# dim=1 将其加在张量的后面