1、numpy的导入

In [2]:
#导入library
import numpy as np

2、创建和生成

从Python列表或元组创建

In [2]:
#一个list
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#二维（多维类似）
#注意，有个小数
np.array([[1,2.,3],[4,5,6]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
#也可指定数据类型
np.array([1,2,3],dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [5]:
#一个tuple
np.array((1.1,2.2))

array([1.1, 2.2])

In [6]:
#转换
np.asarray((1,2,3))

array([1, 2, 3])

In [9]:
np.asarray(([1.,2.,3.],(4.,5.,6.)))

array([[1., 2., 3.],
       [4., 5., 6.]])

使用arange生成一维向量

In [10]:
 np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
#目标的shape需要的元素数量一定要和原始的元素数量相等，小数也可
np.arange(12).reshape(3,4) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.arange(100,124,2).reshape(3,2,2)

array([[[100, 102],
        [104, 106]],

       [[108, 110],
        [112, 114]],

       [[116, 118],
        [120, 122]]])

*使用linspace/logspace生成
前者需要传入3个参数：开头、结尾、数量；后者需要额外传入一个base，默认是10

In [13]:
#线性
np.linspace(0,9,10).reshape(2,5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [14]:
#指数base默认为 10 ,对数
np.logspace(0,9,6,base=np.e).reshape(2,3)

array([[1.00000000e+00, 6.04964746e+00, 3.65982344e+01],
       [2.21406416e+02, 1.33943076e+03, 8.10308393e+03]])

In [15]:
# _ 表示上（最近）一个输出
# logspace 结果 log 后就是上面linspace的结果
np.log(_)

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

使用ones/zeros创建，创建出来的array默认是float类型

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
#像给定向量那样的 0 向量（ones_like 是 1 向量）
np.zeros_like(np.ones((2,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

*使用random生成（最重要）

In [29]:
# 0-1均匀分布
np.random.rand(2,3)

array([[0.75237094, 0.74189089, 0.88757106],
       [0.901947  , 0.99931482, 0.9897973 ]])

In [30]:
#单个数
np.random.rand()

0.2632329218059608

In [31]:
# 0-1均匀分布
np.random.random((3,2))

array([[0.26162016, 0.93085979],
       [0.61167769, 0.20683909],
       [0.99681783, 0.69638689]])

In [32]:
#指定上下界的均匀分布
np.random.uniform(-1,1,(2,3))

array([[-0.39273242, -0.22053619,  0.09082178],
       [-0.93512736,  0.41803348, -0.64152707]])

In [33]:
# 新
# rng是个Generator，可用于生成各种分布
rng = np.random.default_rng(42)
rng

Generator(PCG64) at 0x2098EB30048

In [34]:
#推荐的均匀分布用法
rng.random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [35]:
#可以指定上下界，所以更推荐这种用法
rng.uniform(0,1,(2,3))

array([[0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499]])

In [36]:
#随机整数，不超过给定的值10
np.random.randint(10,size=2)

array([5, 3])

In [37]:
#随机整数，指定上下界和shape
np.random.randint(0,10,(2,3))

array([[9, 9, 9],
       [6, 5, 6]])

In [38]:
#推荐方法，指定大小和上界
rng.integers(10,size=2)

array([7, 6], dtype=int64)

In [39]:
#推荐方法，指定上下界
rng.integers(0,10,(2,3))

array([[4, 8, 5],
       [4, 4, 2]], dtype=int64)

In [40]:
#标准正态分布
np.random.randn(2,4)

array([[-0.39342967, -1.16432078, -0.91656341,  0.1619699 ],
       [ 1.30592957,  1.32507251, -0.1106328 ,  0.86694117]])

In [41]:
#推荐标准正态分布用法
rng.standard_normal((2,4))

array([[ 0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948]])

In [42]:
#高斯分布
np.random.normal(0,1,(3,5))

array([[ 0.50825403,  0.32106575,  2.14665693,  0.73614023, -0.41452973],
       [-0.52550988,  0.90074033, -0.41526796,  1.72000392, -1.6530288 ],
       [ 0.61115251,  0.98569095, -0.06593525, -0.23583292,  1.24069733]])

In [43]:
#推荐的高斯分布用法
rng.normal(0,1,(3,5))

array([[-0.42832782, -0.35213355,  0.53230919,  0.36544406,  0.41273261],
       [ 0.430821  ,  2.1416476 , -0.40641502, -0.51224273, -0.81377273],
       [ 0.61597942,  1.12897229, -0.11394746, -0.84015648, -0.82448122]])

从文件读取

In [45]:
#直接将给定矩阵存为 a.npy
np.save('./data/a',np.array([[1,2,3],[4,5,6]]))

In [ ]:
#加载单个 array
np.load("data/a.npy")

In [ ]:
#可以将多个矩阵存在一起，名为 b.npz
np.savez("./data/b",a=np.arange(12).reshape(3,4),b=np.arange(12.).reshape(4,3))

In [ ]:
#加载多个，可以像字典那样取出对应的 array
arr=np.load("data/b.npz")

3、统计和属性

两个重要特性：按维度（指定axis）求结果、计算后保持维度（keepdims=True)

In [46]:
# 先创建一个Generator
rng = np.random.default_rng(seed=42) #指定seed，保证在同等条件下调参
#再生成一个均匀分布
arr = rng.random((3,4))
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

尺寸相关：包括维度、形状和数据量，其中形状shape用的最多

In [47]:
#维度，array是二维的（两个维度）
arr.ndim

2

In [48]:
#形状，返回一个Tuple
arr.shape

(3, 4)

In [49]:
#数据量
arr.size

12

最值分位：包括最大值、最小值、中位数、其他分位数，其中最大值最小值用的最多

In [50]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [51]:
#所有元素中最大的
arr.max()

0.9756223516367559

In [54]:
#按维度（列）最大值
arr.max(axis=0)
#行
#arr.max(axis=1)

array([0.77395605, 0.97562235, 0.85859792, 0.92676499])

In [55]:
#是否保持原来的维度
#这个需要特别注意下，很多深度学习模型中都需要保持原有的维度进行后续计算
#shape是（3，1），array的shape是（3，4），按行，同时保持了行的维度
arr.min(axis=1,keepdims=True)

array([[0.43887844],
       [0.09417735],
       [0.12811363]])

In [56]:
# 同amax
np.amin(arr,axis=1)

array([0.43887844, 0.09417735, 0.12811363])

In [57]:
#中位数
#其他用法和max，min是一样的
np.median(arr)

0.7292538655248584

In [58]:
#分位数，按列取1/4数
np.quantile(arr,q=0.25,axis=0)

array([0.11114549, 0.44463219, 0.56596886, 0.74171617])

In [59]:
#分位数，按行取3/4，同时保持维度
np.quantile(arr, q=0.75, axis=1, keepdims=True)

array([[0.79511652],
       [0.83345382],
       [0.5694807 ]])

In [60]:
#分位数，注意，分位数可以是0-1之间的任意数字（分位）
#如果是1/2分位，那正好是中位数
np.quantile(arr, q=1/2, axis=1)

array([0.73566204, 0.773602  , 0.41059198])

平均求和标准差：包括平均值、累计求和、方差、标准差等进一步的统计指标，其中平均值使用最多

In [61]:
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [62]:
#平均值
np.average(arr)

0.6051555606435642

In [63]:
#按维度平均（列）
np.average(arr,axis=0)

array([0.33208234, 0.62162891, 0.66351188, 0.80339911])

In [64]:
#另一个计算平均值的API
#它与average的主要区别是，np.average可以指定权重，即可以用于计算加权平均
#一般建议使用average
np.mean(arr,axis=0)

array([0.33208234, 0.62162891, 0.66351188, 0.80339911])

In [65]:
#求和
np.sum(arr,axis=1)

array([2.76880044, 2.61700371, 1.87606258])

In [66]:
#按列累计求和
np.cumsum(arr, axis=0)

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.8681334 , 1.41450079, 1.61973762, 1.48343233],
       [0.99624703, 1.86488673, 1.99053565, 2.41019732]])

In [67]:
#按行累计求和
np.cumsum(arr, axis=1)

array([[0.77395605, 1.21283449, 2.07143241, 2.76880044],
       [0.09417735, 1.0697997 , 1.8309394 , 2.61700371],
       [0.12811363, 0.57849957, 0.94929759, 1.87606258]])

In [68]:
#标准差
np.std(arr)

0.28783096517727075

In [69]:
#按列求标准差
np.std(arr,axis=0)

array([0.3127589 , 0.25035525, 0.21076935, 0.09444968])

In [70]:
#方差
np.var(arr,axis=1)

array([0.02464271, 0.1114405 , 0.0839356 ])

4、形状与转换

 *改变形状，扩展1维度的expand_dims和去除1维度的squeeze高频使用，shape都为1

In [3]:
#换个整数的随机array
rng=np.random.default_rng(seed=42)
arr=rng.integers(1,100,(3,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [4]:
#reshape成另一个形状
#也可以直接变成一维向量
arr.reshape(2,2,3)

array([[[ 9, 77, 65],
        [44, 43, 86]],

       [[ 9, 70, 20],
        [10, 53, 97]]], dtype=int64)

In [5]:
#可偷懒，使用 -1 表示其他维度（此处-1为3），注意，reshape参数可以是tuple或连续整数
arr.reshape((4,-1))

array([[ 9, 77, 65],
       [44, 43, 86],
       [ 9, 70, 20],
       [10, 53, 97]], dtype=int64)

In [6]:
#另一种变换形状的方式——原地变换
#不过不能用-1
arr.resize((4,3))
#注意，上面的reshape会生成一个新的array，但resize不会，所以我们需要用原变量名将他展示出来
arr

array([[ 9, 77, 65],
       [44, 43, 86],
       [ 9, 70, 20],
       [10, 53, 97]], dtype=int64)

In [7]:
#有时候可能需要将多维array打平
arr.ravel()

array([ 9, 77, 65, 44, 43, 86,  9, 70, 20, 10, 53, 97], dtype=int64)

In [9]:
#扩展一个维度，需要（必须）指定维度
np.expand_dims(arr, 1).shape

(4, 1, 3)

In [10]:
expanded=np.expand_dims(arr, axis=(1,3))
expanded.shape

(4, 1, 3, 1)

In [11]:
#去除维度为1的
#如果指定了维度，那就只会去除该维度，指定的维度必须为1
np.squeeze(expanded).shape

(4, 3)

反序

In [13]:
#字符串
s="uevol"
s[::-1]

'loveu'

In [14]:
#数组
lst=[1,"1",5.2]
lst[::-1]

[5.2, '1', 1]

In [113]:
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [114]:
#默认列反序
arr[::-1]

array([[ 4,  2, 11, 19],
       [ 9, 17,  2, 14],
       [ 2, 15, 13,  9]], dtype=int64)

In [115]:
#arr
#行反序,列不变         
arr[::-1,:]

array([[ 4,  2, 11, 19],
       [ 9, 17,  2, 14],
       [ 2, 15, 13,  9]], dtype=int64)

In [116]:
#行变列也变
arr[::-1,::-1]

array([[19, 11,  2,  4],
       [14,  2, 17,  9],
       [ 9, 13, 15,  2]], dtype=int64)

转置

In [25]:
#一维
np.array([1,2]).T.shape

(2,)

In [26]:
arr

array([[ 9, 77, 65],
       [44, 43, 86],
       [ 9, 70, 20],
       [10, 53, 97]], dtype=int64)

In [27]:
#简单用法，把所有维度都给倒过来
arr.T

array([[ 9, 44,  9, 10],
       [77, 43, 70, 53],
       [65, 86, 20, 97]], dtype=int64)

In [28]:
#将shape=(1,1,3,4)的转置后得到shape=(4,3,1,1)
arr.reshape(1,1,3,4).T.shape

(4, 3, 1, 1)

In [29]:
#这种转置方式可以指定axes
#不指定axes时和.T时一样的
np.transpose(arr)

array([[ 9, 44,  9, 10],
       [77, 43, 70, 53],
       [65, 86, 20, 97]], dtype=int64)

In [30]:
#指定axes，不过axes数量必须包含所有维度的序列
#比如两个维度就是（0，1），四个就是（0，1，2，3）
#当然，顺序可以改变，比如下面就是只转置第2个和第3个维度
#注意，只有超过2维时，这样才有意义
np.transpose(arr.reshape(1,1,3,4), axes=(0,2,1,3)).shape

(1, 3, 1, 4)

*5、分解和组合（最重要）

**切片和索引，核心动作概括为：按维度根据start:stop:step操作array（从后往前索引）

In [31]:
rng=np.random.default_rng(42)
arr=rng.random((5,4))
arr

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ]])

In [32]:
#最简单的索引，取第0行
arr[0]

array([0.77395605, 0.43887844, 0.85859792, 0.69736803])

In [33]:
#最简单的切片，取第0行第1个元素
arr[0,1]

0.4388784397520523

In [34]:
#然后带点范围 第1-2行
arr[1:3]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [35]:
#离散也可以：第1，3行
arr[[1,3]]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872]])

In [36]:
#再来加点维度：第1-2行，第1列
arr[1:3,1]

array([0.97562235, 0.45038594])

In [39]:
#离散也是一样：第1，3行，第0列
arr[[1,3],[0]]

array([0.09417735, 0.64386512])

In [40]:
#还可以有简写：到最后或到开始。如第3行到最后一行
arr[3:]

array([[0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ]])

In [41]:
#开始到第3行，第1-3列
arr[:3,1:3]

array([[0.43887844, 0.85859792],
       [0.97562235, 0.7611397 ],
       [0.45038594, 0.37079802]])

In [42]:
#还可以跳跃，步长：start:stop:step，第1行到第4行，间隔为2，即1、3行
arr[1:4:2]

array([[0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872]])

In [43]:
#也可加上列，第1、3行，第0、2列
arr[1:4:2, 0:3:2]

array([[0.09417735, 0.7611397 ],
       [0.64386512, 0.4434142 ]])

In [44]:
#第一列的值，其实是所有其他维度第1维的值
arr[...,1]

array([0.43887844, 0.97562235, 0.45038594, 0.82276161, 0.06381726])

In [45]:
#与上面类似，但用的更多
arr[:,1]

array([0.43887844, 0.97562235, 0.45038594, 0.82276161, 0.06381726])

In [ ]:
拼接：np.concatenate和np.stack，前者是拼接，后者是堆叠（会增加一个维度），都可以指定维度。

In [46]:
rng=np.random.default_rng(42)
arr1=rng.random((2,3))
arr2=rng.random((2,3))
arr1,arr2

(array([[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235]]),
 array([[0.7611397 , 0.78606431, 0.12811363],
        [0.45038594, 0.37079802, 0.92676499]]))

In [48]:
#默认沿axis=0（列）连接
np.concatenate((arr1,arr2))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499]])

In [49]:
#竖直按行顺序拼接
#注意：vstack虽然看起来是stack，但其实它是concatenate
np.vstack((arr1,arr2))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499]])

In [50]:
#沿axis=1（行）拼接   (hstack)
np.concatenate((arr1,arr2),axis=1)

array([[0.77395605, 0.43887844, 0.85859792, 0.7611397 , 0.78606431,
        0.12811363],
       [0.69736803, 0.09417735, 0.97562235, 0.45038594, 0.37079802,
        0.92676499]])

In [51]:
#堆叠，默认根据axis=0进行   (dstack)
np.stack((arr1,arr2)).shape

(2, 2, 3)

In [55]:
#堆叠，根据axis=2
np.stack((arr1,arr2),axis=2)

array([[[0.77395605, 0.7611397 ],
        [0.43887844, 0.78606431],
        [0.85859792, 0.12811363]],

       [[0.69736803, 0.45038594],
        [0.09417735, 0.37079802],
        [0.97562235, 0.92676499]]])

In [56]:
# _ 表示上一个Cell的输出结果
_.shape

(2, 3, 2)

重复：是一个维度一个维度依次重复，而不是整个array重复

In [57]:
rng=np.random.default_rng(42)
arr=rng.integers(0,10,(3,4))
arr

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]], dtype=int64)

In [58]:
#在axis=0（按列）上重复2次
np.repeat(arr,2,axis=0)

array([[0, 7, 6, 4],
       [0, 7, 6, 4],
       [4, 8, 0, 6],
       [4, 8, 0, 6],
       [2, 0, 5, 9],
       [2, 0, 5, 9]], dtype=int64)

In [59]:
#在axis=1（按行）上重复3次
np.repeat(arr,3,axis=1)

array([[0, 0, 0, 7, 7, 7, 6, 6, 6, 4, 4, 4],
       [4, 4, 4, 8, 8, 8, 0, 0, 0, 6, 6, 6],
       [2, 2, 2, 0, 0, 0, 5, 5, 5, 9, 9, 9]], dtype=int64)

分拆：分拆的axis是对该维度进行拆分

In [60]:
rng=np.random.default_rng(42)
arr=rng.integers(1,100,(6,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97],
       [73, 76, 72, 78],
       [51, 13, 84, 45],
       [50, 37, 19, 92]], dtype=int64)

In [61]:
#默认切分列（axis=0），切成3份
np.split(arr,3)

[array([[ 9, 77, 65, 44],
        [43, 86,  9, 70]], dtype=int64),
 array([[20, 10, 53, 97],
        [73, 76, 72, 78]], dtype=int64),
 array([[51, 13, 84, 45],
        [50, 37, 19, 92]], dtype=int64)]

In [63]:
#（axis=1）切分行
np.split(arr,2,axis=1)

[array([[ 9, 77],
        [43, 86],
        [20, 10],
        [73, 76],
        [51, 13],
        [50, 37]], dtype=int64),
 array([[65, 44],
        [ 9, 70],
        [53, 97],
        [72, 78],
        [84, 45],
        [19, 92]], dtype=int64)]

*6、筛选和过滤

In [64]:
rng=np.random.default_rng(42)
arr=rng.integers(1,100,(3,4))
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

条件筛选：where分别返回各维度的index，赋值的是不满足条件的

In [65]:
#条件筛选，可以直接在整个array上使用条件
arr>50

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [66]:
#返回满足条件的索引，因为是两个维度，所以会返回两组结果   (上下对)
np.where(arr>50)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 1, 3, 2, 3], dtype=int64))

In [67]:
#不满足条件的赋值，将<=50的替换为-1
np.where(arr>50, arr, -1)

array([[-1, 77, 65, -1],
       [-1, 86, -1, 70],
       [-1, -1, 53, 97]], dtype=int64)

提取（按条件）：返回一维向量

In [68]:
#提取指定条件的值
np.extract(arr>50, arr)

array([77, 65, 86, 70, 53, 97], dtype=int64)

In [69]:
#唯一值，是另一种形式的提取
np.unique(arr)

array([ 9, 10, 20, 43, 44, 53, 65, 70, 77, 86, 97], dtype=int64)

抽样（按分布）：集合要求为一维向量（一般是数据的index）

In [70]:
rng=np.random.default_rng(42)
rng.choice(4, 2, replace=False, p=[0.1,0.2,0.3,0.4])
#第一个参数是要抽样的集合，如果是一个整数，则表示从0到该值
#第二个参数是样本大小
#第三个参数表示结果是否可以重复
#第四个参数表示出现的概率，长度和第一个参数一样

#由于（0 1 2 3）中2和3的概率比较高，自然就选择了2和3

array([3, 2], dtype=int64)

In [71]:
#旧的API
#如果是抽样语料的index，更多的方法是这样：   （抽样语料？）
data_size=10000
np.random.choice(data_size, 50, replace=False)

array([9561,  586, 5396, 1311, 6939, 7667, 6801, 7293, 5478, 3934, 5656,
       5447, 7093, 1618, 6433, 3128,  974, 5088, 2731, 4954, 4715, 2003,
       9298, 4471, 1310,  590, 8941, 6688, 3514, 6904, 8142, 5968, 4432,
       3277, 7227, 3427, 4818, 1945, 1607, 5877, 8807,   51, 6821, 6715,
       1331, 4250, 7288,  846, 2577,  435])

最值index（特殊值）

In [72]:
rng=np.random.default_rng(42)
arr=rng.uniform(1,100,(3,4))
arr

array([[77.62164881, 44.44896554, 86.00119407, 70.03943488],
       [10.32355744, 97.58661281, 76.3528305 , 78.82036622],
       [13.68324963, 45.58820785, 37.7090044 , 92.7497339 ]])

In [73]:
#所有值中最大的index
np.argmax(arr)

5

In [74]:
#按列（axis=0）最大值的index
np.argmax(arr,axis=0)

array([0, 1, 0, 2], dtype=int64)

In [75]:
#按行（axis=1）最小值的index
np.argmin(arr,axis=1)

array([1, 0, 0], dtype=int64)

In [76]:
#默认按行（axis=1）排序的索引
np.argsort(arr)

array([[1, 3, 0, 2],
       [0, 2, 3, 1],
       [0, 2, 1, 3]], dtype=int64)

In [78]:
#默认按列（axis=0）排序的索引
np.argsort(arr,axis=0)

array([[1, 0, 2, 0],
       [2, 2, 1, 1],
       [0, 1, 0, 2]], dtype=int64)

7、矩阵和运算

算数  

In [79]:
rng=np.random.default_rng(42)
arr=rng.integers(1,20,(3,4))
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [80]:
#+-*/四则运算，就跟两个数字计算一样
arr * 2

array([[ 4, 30, 26, 18],
       [18, 34,  4, 28],
       [ 8,  4, 22, 38]], dtype=int64)

In [81]:
#平方
arr ** 2

array([[  4, 225, 169,  81],
       [ 81, 289,   4, 196],
       [ 16,   4, 121, 361]], dtype=int64)

In [82]:
#开方
np.sqrt(arr)

array([[1.41421356, 3.87298335, 3.60555128, 3.        ],
       [3.        , 4.12310563, 1.41421356, 3.74165739],
       [2.        , 1.41421356, 3.31662479, 4.35889894]])

In [84]:
#四舍五入 
np.round(np.sqrt(arr),2)

array([[1.41, 3.87, 3.61, 3.  ],
       [3.  , 4.12, 1.41, 3.74],
       [2.  , 1.41, 3.32, 4.36]])

In [85]:
#floor “地板”舍掉小数位
np.floor(np.sqrt(arr))

array([[1., 3., 3., 3.],
       [3., 4., 1., 3.],
       [2., 1., 3., 4.]])

In [88]:
#ceil “天花板”有小数位的+1 
np.ceil(np.sqrt(arr))

array([[2., 4., 4., 3.],
       [3., 5., 2., 4.],
       [2., 2., 4., 5.]])

In [86]:
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [87]:
# mod <=> x % 3   
np.mod(arr, 3)

array([[2, 0, 1, 0],
       [0, 2, 2, 2],
       [1, 2, 2, 1]], dtype=int64)

In [89]:
#mod运算可以指定多个被除数   对应除
np.mod(arr, arr-5)

array([[-1,  5,  5,  1],
       [ 1,  5, -1,  5],
       [ 0, -1,  5,  5]], dtype=int64)

广播：较小的数组会在较大的数组上进行广播，以便适配对方的形状（一维对应，一维为1）

In [90]:
rng=np.random.default_rng(42)
a=rng.integers(1,100,(3,4))
a

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [91]:
#广播，后面的被当作 1 行 4 列
a + [1,2,3,4]

array([[ 10,  79,  68,  48],
       [ 44,  88,  12,  74],
       [ 21,  12,  56, 101]], dtype=int64)

In [92]:
#或者这样广播，后面的被当作 3 行 1 列
a + [[1],[2],[3]]

array([[ 10,  78,  66,  45],
       [ 45,  88,  11,  72],
       [ 23,  13,  56, 100]], dtype=int64)

In [94]:
#之前的取余也是可以的
np.mod(a,[1,2,3,4])

array([[0, 1, 2, 0],
       [0, 0, 0, 2],
       [0, 0, 2, 1]], dtype=int64)

矩阵

In [96]:
rng=np.random.default_rng(42)
a=rng.integers(1,10,(3,2))
b=rng.integers(1,10,(2,4))
c=rng.integers(1,10,(3,3))
a,b,c

(array([[1, 7],
        [6, 4],
        [4, 8]], dtype=int64),
 array([[1, 7, 2, 1],
        [5, 9, 7, 7]], dtype=int64),
 array([[7, 8, 5],
        [2, 8, 5],
        [5, 4, 2]], dtype=int64))

In [97]:
# array 乘法
np.dot(a,b) #同a.dot(b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [98]:
#矩阵乘法
#与 dot 的主要区别是：如果维度 >2，dot 只考虑最后的维度，而 matmul则考虑所有维度
np.matmul(a,b)   #同a @ b

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [99]:
#高纬度下dot和matmul的区别
#ijk,lkm -> ijlm
np.dot(np.ones((5,2,3)),np.ones((4,3,6))).shape

(5, 2, 4, 6)

In [100]:
# ijk，ikl -> ijl
np.matmul(np.ones((5,2,3)),np.ones((4,3,6))).shape

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (5,2,3)->(5,newaxis,newaxis) (4,3,6)->(4,newaxis,newaxis) and requested shape (2,6)

In [101]:
# ijk，ikl -> ijl
np.matmul(np.ones((4,2,3)),np.ones((4,3,6))).shape

(4, 2, 6)

In [102]:
#点积
np.vdot(a,a)

182

In [103]:
#就是点积
np.sum(a*a)

182

In [104]:
#内积
np.inner(a,a)

array([[50, 34, 60],
       [34, 52, 56],
       [60, 56, 80]], dtype=int64)

In [106]:
#就是内积
#a.dot(a,T)

In [107]:
#行列式
np.linalg.det(c)

-20.000000000000007

In [109]:
#逆矩阵（方阵）
np.linalg.inv(c)

array([[ 2.00000000e-01, -2.00000000e-01,  2.53765263e-16],
       [-1.05000000e+00,  5.50000000e-01,  1.25000000e+00],
       [ 1.60000000e+00, -6.00000000e-01, -2.00000000e+00]])

In [110]:
#查看用法
np.argmax?

——>总结

——>练习