In [3]:
import torch

In [5]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad = True)
b = torch.randn(3,requires_grad = True)
z = torch.matmul(x,w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [6]:
print('Gradient function for z =',z.grad_fn)
print('Gradient function for loss = ',loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x0000020CB4C4FAF0>
Gradient function for loss =  <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000020CB4C4F880>


In [11]:
loss.backward()  #可以打印所有能计算出梯度的父节点的梯度
print(w.grad)
print(b.grad)

tensor([[0.0229, 0.0461, 0.2367],
        [0.0229, 0.0461, 0.2367],
        [0.0229, 0.0461, 0.2367],
        [0.0229, 0.0461, 0.2367],
        [0.0229, 0.0461, 0.2367]])
tensor([0.0229, 0.0461, 0.2367])


In [12]:
z = torch.matmul(x,w)+b  ##父节点中有一个requires为true，整个结果都为true
print(z.requires_grad)

with torch.no_grad():    
    z = torch.matmul(x,w)+b
print(z.requires_grad)

True
False


In [13]:
z = torch.matmul(x,w)+b
z_det = z.detach()  ##分离，调用detach函数得到新的节点
print(z_det.requires_grad)

False


In [16]:
inp = torch.eye(5,requires_grad = True)  ##传入一个对角张量
out = (inp+1).pow(2)                     ##先一个加法操作，在一个平方操作
out.backward(torch.ones_like(inp),retain_graph=True)  ##这个全1的矩阵充当vector v
print("First call\n",inp.grad)
out.backward(torch.ones_like(inp),retain_graph=True)
print("\nSecond call\n",inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp),retain_graph=True)
print("\nCall after zeroing gradients\n",inp.grad)

First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])


In [5]:
inp = torch.eye(5,requires_grad = True)  ##传入一个对角张量
out = (inp+1).pow(2)  
print(out)

tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)


In [6]:
inp = torch.eye(5,requires_grad = True)
print(inp)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)
