In [52]:
import torch
import torch.autograd

In [3]:
def func(x):
  return x.exp().sum(dim=1)  ##exp 指数运算，sum(dim=1)每一行之和
x = torch.randn(2, 3)

In [4]:
x

tensor([[ 0.5742, -0.2570, -0.0212],
        [-1.3974, -0.2553, -0.5087]])

In [6]:
y = func(x)
y

tensor([3.5282, 1.6232])

In [34]:
torch.autograd.functional.jacobian(func, x)   ##居然需要写全才能用，白白浪费半小时查如何调用jacobian

tensor([[[1.7758, 0.7734, 0.9791],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.2472, 0.7747, 0.6013]]])

In [32]:
torch.autograd.functional.jacobian

<function torch.autograd.functional.jacobian(func, inputs, create_graph=False, strict=False, vectorize=False, strategy='reverse-mode')>

In [35]:
jacobian(func, x)

NameError: name 'jacobian' is not defined

In [37]:
x,y

(tensor([[ 0.5742, -0.2570, -0.0212],
         [-1.3974, -0.2553, -0.5087]]),
 tensor([3.5282, 1.6232]))

In [39]:
a = torch.randn(3)
a

tensor([-0.8635, -1.5148, -1.5851])

In [40]:
def func(x):
    return a+x

In [41]:
x = torch.randn(3)
x

tensor([-1.2974,  0.4625,  2.0349])

In [44]:
func(x)

tensor([-2.1610, -1.0523,  0.4497])

In [43]:
torch.autograd.functional.jacobian(func,x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [45]:
a

tensor([-0.8635, -1.5148, -1.5851])

In [46]:
x = torch.randn(3,requires_grad=True)

In [47]:
y = func(x)

In [48]:
y

tensor([-1.6689, -1.1799, -2.9121], grad_fn=<AddBackward0>)

In [49]:
y.backward()  ##y是一个张量不是标量，直接调用bacaward会报错

RuntimeError: grad can be implicitly created only for scalar outputs

In [50]:
y.backward(torch.ones_like(y))

In [51]:
x.grad

tensor([1., 1., 1.])

In [58]:
torch.ones_like(y) @ torch.autograd.functional.jacobian(func,x)

tensor([1., 1., 1.])

In [71]:
a = torch.randn(2,3,requires_grad = True)
b = torch.randn(3,2,requires_grad = True)

In [72]:
a,b

(tensor([[ 0.5296,  0.9254,  0.9863],
         [-0.0330,  0.9406,  1.6382]], requires_grad=True),
 tensor([[-0.0144,  0.8200],
         [-0.1409,  1.1454],
         [-1.6455,  1.6617]], requires_grad=True))

In [73]:
y = a @ b

In [74]:
y.backward(torch.ones_like(y))

In [75]:
print(a.grad)

tensor([[0.8056, 1.0044, 0.0162],
        [0.8056, 1.0044, 0.0162]])


In [76]:
b.grad

tensor([[0.4966, 0.4966],
        [1.8660, 1.8660],
        [2.6245, 2.6245]])

In [77]:
def func(a):
    return a @ b

In [78]:
a

tensor([[ 0.5296,  0.9254,  0.9863],
        [-0.0330,  0.9406,  1.6382]], requires_grad=True)

In [79]:
func(a)

tensor([[-1.7610,  3.1330],
        [-2.8279,  3.7725]], grad_fn=<MmBackward0>)

In [80]:
func(a[0])

tensor([-1.7610,  3.1330], grad_fn=<MvBackward0>)

In [82]:
torch.ones_like(func(a[0])) @ torch.autograd.functional.jacobian(func,a[0])

tensor([0.8056, 1.0044, 0.0162])

In [83]:
a.grad

tensor([[0.8056, 1.0044, 0.0162],
        [0.8056, 1.0044, 0.0162]])

In [84]:
torch.ones_like(func(a[0])) @ torch.autograd.functional.jacobian(func,a[1])

tensor([0.8056, 1.0044, 0.0162])

In [85]:
a @ b

tensor([[-1.7610,  3.1330],
        [-2.8279,  3.7725]], grad_fn=<MmBackward0>)

In [86]:
a

tensor([[ 0.5296,  0.9254,  0.9863],
        [-0.0330,  0.9406,  1.6382]], requires_grad=True)

In [87]:
b

tensor([[-0.0144,  0.8200],
        [-0.1409,  1.1454],
        [-1.6455,  1.6617]], requires_grad=True)

In [88]:
def func(b):
    return a @ b

In [89]:
##b的第0列梯度
torch.ones_like(func(b[:,0])) @ torch.autograd.functional.jacobian(func,b[:,0])

tensor([0.4966, 1.8660, 2.6245])

In [90]:
b.grad

tensor([[0.4966, 0.4966],
        [1.8660, 1.8660],
        [2.6245, 2.6245]])

In [91]:
##b的第1列梯度
torch.ones_like(func(b[:,1])) @ torch.autograd.functional.jacobian(func,b[:,1])

tensor([0.4966, 1.8660, 2.6245])