1 Pytorch的介绍与张量的创建

王汝嘉 2022-07-12

张量是一个多维数组，和numpy中的array数组 是十分类似的。
同时pytorch和tensorflow中的api设计也和numpy中的很想，但是区别在于numpy中的数组是不能做微分的，但是pytorch和tensorflow是可以的。
微分是神经网络训练时候的必要操作，我们在反向传播的时候需要根据微分来计算梯度，传回梯度来更新参数的数值。

In [1]:
#导入pytorch和numpy
import torch
import numpy as np

创建张量tensor

将python中的列表list转化成tensor

In [2]:
a=[1,2,3.]

# 注意，3的后面加了个点 也就是将list中数字的数据类型从int 变成了 float 不加.就为float

In [4]:
type(a)

list

In [7]:
b = torch.tensor(a)
b

tensor([1., 2., 3.])

In [8]:
type(b)

torch.Tensor

In [9]:
# .dtype 是ptorch中特有的 用来查看一个变量的数据类型的方法

In [10]:
b.dtype

torch.float32

创建numpy数组 将numpy数组转化为tensor

In [15]:
np.random.normal(2)

3.4830505405269583

In [16]:
np.random.normal((2,3))

array([2.63093775, 2.7393316 ])

In [17]:
### 问题这个（2，3）具体指的是什么含义呢？？？

In [18]:
c=np.random.normal((2,3))
c

array([1.59830635, 2.60125494])

In [19]:
### 问题 numpy之中如何查看数据类型？？？

In [20]:
d=torch.tensor(c)
d

tensor([1.5983, 2.6013], dtype=torch.float64)

In [21]:
d.dtype

torch.float64

使用pytorch自带的api去创建张量

In [30]:
#全一张量
e = torch.ones_like((2，2))
e

SyntaxError: invalid character in identifier (<ipython-input-30-b90cd4711318>, line 2)

In [23]:
#注意上面的写法是错误 使用torch的api来创建张量 必须传入一个张量

In [24]:
e = torch.ones_like(d)
e

tensor([1., 1.], dtype=torch.float64)

In [25]:
#全零张量
f = torch.zeros_like(d)
f

tensor([0., 0.], dtype=torch.float64)

In [26]:
# 随机数张量
g = torch.rand_like(d)
g

tensor([0.4942, 0.2603], dtype=torch.float64)

根据形状来创建张量

形状是shape 也就是对于一个张量来说 它是几行几列的

In [259]:
### 小实验，请你根据代码来验证，（2，2） 一个二维的形状， 第一个指代什么含义？第二个指代什么含义？ （是行，还是列）

In [260]:
#torch.rand() api

In [261]:
h = torch.rand((2,2))  #传入一个tuple 元组来表示形状
h

tensor([[0.5031, 0.9854],
        [0.5554, 0.0460]])

In [262]:
i = torch.rand([2,2]) # 传入一个list 列表来表示形状
i

tensor([[0.5627, 0.3234],
        [0.4329, 0.1213]])

In [263]:
### 小实验，验证用{}  集合来表示形状是可以的吗？

In [264]:
k = torch.rand((2,3,))
k

tensor([[0.9741, 0.5980, 0.6600],
        [0.3820, 0.9015, 0.0918]])

In [265]:
#上面要积累一个小技巧，在3之后加一个，也是可以的 并不会影响张量的创建

In [266]:
# torch.ones()  api

In [267]:
l = torch.ones((2,3))
l

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [268]:
# torch.zeros() api

In [269]:
m = torch.zeros([2,3])
m

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [270]:
#注意！使用形状来创建张量的时候，并不会给出dtype    那么该如何查看你创建的变量的数据类型呢？

In [271]:
#同样使用pytorch中特有的dtype工具

In [272]:
m.dtype

torch.float32

张量的属性
    
    我们创建了一个张量 这个张量具有哪些属性呢？

In [273]:
a = torch.rand((2,3))
a

tensor([[0.2158, 0.8105, 0.1524],
        [0.1915, 0.4596, 0.2673]])

In [274]:
# 数据类型
a.dtype

torch.float32

In [275]:
# shape 形状
a.shape

torch.Size([2, 3])

In [276]:
# device 设备 
    # 创建的这个张量储存在什么设备上 是cpu 还是 gpu
a.device

device(type='cpu')

In [277]:
#如何将张量移动到gpu上？
a = a.to('cuda')
a.device

device(type='cuda', index=0)

积累一个代码之中将将数据移动到gpu上的常用语句

In [278]:
if torch.cuda.is_available():
    a = a.to('cuda')
# 若是一机多卡 那么就cuda0 cuda1 依次往下 也可以直接cuda 让它来自己默认存放

常用的tensor相关的操作：

判断操作

In [279]:
# is_tensor(obj)
torch.is_tensor(a)

True

In [280]:
# is_complex(obj) 判断是否是复数 complex32 complex64
torch.is_complex(a)

False

In [281]:
# is_floating_point(obj) 判断是否是浮点型数据
torch.is_floating_point(a)

True

In [282]:
# is_nonzero(obj) 判断是空数据
torch.is_nonzero(a)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [283]:
#注意 is_nozero() 
#Returns True if the input is a single element tensor which is not equal to zero after type conversions.
#i.e. not equal to torch.tensor([0.]) or torch.tensor([0]) or torch.tensor([False]).
#Throws a RuntimeError if torch.numel() != 1 (even in case of sparse tensors).

In [284]:
b = torch.tensor(1)
b

tensor(1)

In [285]:
c=torch.is_nonzero(b)
d=torch.is_nonzero(torch.tensor([0.]))
e=torch.is_nonzero(torch.tensor([0]))
f=torch.is_nonzero(torch.tensor([False]))
c,d,e,f

(True, False, False, False)

In [286]:
# numel()  一个重要的操作 number of someobj 计算一个张量之中所含元素的个数
a = torch.rand((2,3))
a

tensor([[0.0665, 0.0171, 0.6766],
        [0.9688, 0.1387, 0.6380]])

In [287]:
a.numel()

6

In [288]:
a.shape

torch.Size([2, 3])

In [289]:
# 可以发现 2*3 = 6

主要的操作

In [290]:
#torch.zeros()
#torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
a = torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [291]:
a.dtype   #默认的数据类型

torch.float32

In [292]:
b = torch.zeros((2,3),dtype=torch.int32)
b

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [293]:
c = torch.zeros((2,3),dtype=torch.float64)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [294]:
#torch.zeros_like(obj)
d = torch.rand((2,3))
d

tensor([[0.8075, 0.7379, 0.2089],
        [0.1153, 0.7251, 0.7343]])

In [295]:
e = torch.zeros_like(d)
e

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [296]:
### 请你在下方补充完整 下面两个api的示例 随便创建张量的形状

In [297]:
# torch.ones()

In [298]:
# torch.ones_like()

In [299]:
# torch.arange()    一个在设置训练轮数时的重要函数 默认会返回一个从0开始的有序的序列
# torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [300]:
a = torch.arange(5)
a

tensor([0, 1, 2, 3, 4])

In [301]:
#所以默认从0开始。    当然你也可以自己指定

In [302]:
b = torch.arange(start=2,end=5)
b

tensor([2, 3, 4])

In [303]:
#指定步长
c = torch.arange(0,5,step=2)
c

tensor([0, 2, 4])

In [304]:
#值得注意的是 这里使用了简写 简写的语义对应是根据顺序来的

In [305]:
d = torch.arange(0,5,1,).dtype
d

torch.int64

In [306]:
# 也就是说默认为int64类型

In [307]:
e = torch.arange(0,5,1,dtype=torch.float32)
e

tensor([0., 1., 2., 3., 4.])

In [308]:
# requires_grad    是不是需要梯度  
# 在训练网络网络的时候 数据是一定要有梯度的 因为有了梯度 在反向传播的时候传播梯度 才能进行参数的更新 训练才会有效果
# 但是在推理网络的时候  数据是不需要梯度的

In [309]:
f = torch.arange(0,5,1,requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [310]:
#经由上面的报错信息可知  只有浮点类型和负数类型才能具有梯度

In [311]:
f = torch.arange(0,5,1,dtype=torch.float32,requires_grad=True)
f

tensor([0., 1., 2., 3., 4.], requires_grad=True)

In [312]:
# torch.range()   arange()的一个变体
# torch.range(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [313]:
a = torch.range(start=0,end=5)
a

<ipython-input-313-5e210a0f0d25>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(start=0,end=5)


tensor([0., 1., 2., 3., 4., 5.])

In [314]:
# 哦！根据信息可知，以后torch.range()方法要被删掉了

In [315]:
### 那请你仔细看上一个代码片段或者查阅官网使用手册，写出arange 和 range最大的区别是什么？

积累一个在训练代码过程中经常使用的一个代码语句

In [316]:
for i in torch.arange(10):
    print("epoch:",i)

epoch: tensor(0)
epoch: tensor(1)
epoch: tensor(2)
epoch: tensor(3)
epoch: tensor(4)
epoch: tensor(5)
epoch: tensor(6)
epoch: tensor(7)
epoch: tensor(8)
epoch: tensor(9)


In [317]:
### 请你查阅官网自己学习下面两个api,并将示例写在下方

In [318]:
# torch.linspace()

In [319]:
# torch.logspace()

In [320]:
#  torch.eye()      对角线为一 其余为零 的特殊矩阵
# torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [35]:
a = torch.eye(5)
a

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [322]:
# 默认创建为一个方阵 但是也是可以进行改变的形状的

In [323]:
b = torch.eye(5,6)
b

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [324]:
# 也就是还是保持对角线设置为0  其余设置为1的原则

In [325]:
# torch.full()   给形状并且赋值的方法
# torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [326]:
a = torch.full((5,6),fill_value=3)
a

tensor([[3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3]])

In [327]:
### 请你思考 如何使用torch.ones api来实现上边的效果呢？

In [328]:
b = torch.full((5,6),1.111111)
b

tensor([[1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111],
        [1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111],
        [1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111],
        [1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111],
        [1.1111, 1.1111, 1.1111, 1.1111, 1.1111, 1.1111]])

In [329]:
# torch.full_like()

In [330]:
a = torch.full_like(b,2.222222)
a

tensor([[2.2222, 2.2222, 2.2222, 2.2222, 2.2222, 2.2222],
        [2.2222, 2.2222, 2.2222, 2.2222, 2.2222, 2.2222],
        [2.2222, 2.2222, 2.2222, 2.2222, 2.2222, 2.2222],
        [2.2222, 2.2222, 2.2222, 2.2222, 2.2222, 2.2222],
        [2.2222, 2.2222, 2.2222, 2.2222, 2.2222, 2.2222]])

indexing slicing joining multating ops

索引 切片 聚合 旋转

In [331]:
# torch.cat()   concat函数 一个有些难度的函数
# torch.cat(tensors, dim=0, *, out=None) 
# Concatenates the given sequence of seq tensors in the given dimension. 
# All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [332]:
# torch.cat()方法 要求相cat的两个张量 除了被相加的那个维度的形状可以不同之外 其余维度的形状必须相同

In [333]:
# 仅能在第0维进行concat()  最后的效果是 行数不变 列数增加
a = torch.full((2,2),2)
a

tensor([[2, 2],
        [2, 2]])

In [334]:
b = torch.full((3,2),3)
b

tensor([[3, 3],
        [3, 3],
        [3, 3]])

In [335]:
# 因为a的第0维为2 b的第0维为3 a的第1维为2 b的第一维为2
# a，b的第0维是不同的 a,b的第1维是相同的 所以仅能在第0维进行concat 以此来满足除了被concat的维度形状可以不同之外 其它的维度必须相同的原则

In [336]:
torch.cat((a,b),dim=0)

tensor([[2, 2],
        [2, 2],
        [3, 3],
        [3, 3],
        [3, 3]])

In [337]:
# 仅能在第1维进行concat()    最后的效果是 行数不变 列数增加

In [338]:
c = torch.full((2,2),2)
c

tensor([[2, 2],
        [2, 2]])

In [339]:
d = torch.full((2,3),3)
d

tensor([[3, 3, 3],
        [3, 3, 3]])

In [340]:
torch.cat([c,d],dim=1)

tensor([[2, 2, 3, 3, 3],
        [2, 2, 3, 3, 3]])

In [341]:
### 请判断利用torch.cat() api 将下面三个tensor concat起来

In [342]:
a = torch.full((2,2,2),1)
a

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [343]:
b = torch.full((2,2,3),2)
b

tensor([[[2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2]]])

In [344]:
c = torch.full((2,2,4),3)
c

tensor([[[3, 3, 3, 3],
         [3, 3, 3, 3]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3]]])