In [7]:
import torch
import torch.autograd

In [8]:
def func(x):
  return x.exp().sum(dim=1)  #sum(dim=1)对每一行求和

In [9]:
x = torch.randn(2, 3)

In [10]:
x

tensor([[-0.2737,  0.7202, -0.9718],
        [-0.9212,  1.2268,  0.5909]])

In [12]:
y=func(x)

In [13]:
y

tensor([3.1938, 5.6139])

In [17]:
torch.autograd.functional.jacobian(func, x) #参数主要是(func,inputs)，func是一个函数，输入形式是tensor，返回形式是一个tensor或者一系列tensor，inputs就是要传入func函数中的输入

tensor([[[0.7606, 2.0548, 0.3784],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.3980, 3.4103, 1.8056]]])

#上边就是雅可比矩阵

In [18]:
def func(x):
    return 

In [19]:
a=torch.randn(3)

In [20]:
a

tensor([-0.3342,  0.1808, -1.9951])

In [21]:
def func(x):
    return a+x

In [22]:
x=torch.randn(3)

In [23]:
x

tensor([-0.2121, -2.1432, -0.5180])

In [24]:
func(x)

tensor([-0.5463, -1.9624, -2.5130])

In [25]:
jacobian(func,x)

NameError: name 'jacobian' is not defined

In [26]:
torch.autograd.functional.jacobian(func, x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [27]:
#backword()方法
a

tensor([-0.3342,  0.1808, -1.9951])

In [28]:
x = torch.randn(3,requires_grad=True)

In [29]:
y=func(x)

In [30]:
y

tensor([-0.0829, -0.2615, -3.8747], grad_fn=<AddBackward0>)

In [31]:
y.backword() #用backword()函数计算x的梯度。但直接这样调用会报错，y现在是张量不是标量

AttributeError: 'Tensor' object has no attribute 'backword'

In [32]:
y.backward(torch.ones_like(y))

In [33]:
x.grad

tensor([1., 1., 1.])

In [35]:
#雅可比方法
torch.ones_like(y) @ torch.autograd.functional.jacobian(func,y)#前者充当vector，@表示相乘

tensor([1., 1., 1.])

#以上是向量对向量的导数求法，下边是矩阵对矩阵

In [36]:
a = torch.randn(2,3,requires_grad = True)
b = torch.randn(3,2,requires_grad = True)

In [37]:
a

tensor([[ 1.1534, -0.0693, -0.0799],
        [-0.8072,  0.5023,  1.0066]], requires_grad=True)

In [38]:
b

tensor([[-0.6340,  0.7446],
        [ 0.2974, -0.3235],
        [-0.0979,  1.1610]], requires_grad=True)

In [39]:
a@b# @表示乘法

tensor([[-0.7440,  0.7885],
        [ 0.5626,  0.4051]], grad_fn=<MmBackward0>)

In [40]:
y=a@b

In [41]:
y.backword()

AttributeError: 'Tensor' object has no attribute 'backword'

In [42]:
y.backward(torch.ones_like(y))

In [43]:
a.grad

tensor([[ 0.1107, -0.0261,  1.0632],
        [ 0.1107, -0.0261,  1.0632]])

In [44]:
b.grad

tensor([[0.3462, 0.3462],
        [0.4329, 0.4329],
        [0.9266, 0.9266]])

In [45]:
def func(a):
    return a @ b

In [46]:
a

tensor([[ 1.1534, -0.0693, -0.0799],
        [-0.8072,  0.5023,  1.0066]], requires_grad=True)

In [47]:
func(a)

tensor([[-0.7440,  0.7885],
        [ 0.5626,  0.4051]], grad_fn=<MmBackward0>)

In [48]:
 func(a[0]) #先算a的第一行，将矩阵输出变成向量输出

tensor([-0.7440,  0.7885], grad_fn=<MvBackward0>)

In [49]:
torch.ones_like(func(a[0]))@torch.autograd.functional.jacobian(func,a[0]) #前者就是vector，就是dl/dy的梯度，默认是全1的张量

tensor([ 0.1107, -0.0261,  1.0632])

In [50]:
a.grad

tensor([[ 0.1107, -0.0261,  1.0632],
        [ 0.1107, -0.0261,  1.0632]])

In [51]:
torch.ones_like(func(a[1])) @ torch.autograd.functional.jacobian(func,a[1])

tensor([ 0.1107, -0.0261,  1.0632])

In [52]:
a@b

tensor([[-0.7440,  0.7885],
        [ 0.5626,  0.4051]], grad_fn=<MmBackward0>)

In [53]:
a

tensor([[ 1.1534, -0.0693, -0.0799],
        [-0.8072,  0.5023,  1.0066]], requires_grad=True)

In [54]:
b

tensor([[-0.6340,  0.7446],
        [ 0.2974, -0.3235],
        [-0.0979,  1.1610]], requires_grad=True)

In [55]:
 def func(b):
    return a@b

In [56]:
torch.ones_like(func(b[:,0])) @ torch.autograd.functional.jacobian(func,b[:,0])
#b[:,0]表示b的第一列

tensor([0.3462, 0.4329, 0.9266])

In [57]:
b.grad

tensor([[0.3462, 0.3462],
        [0.4329, 0.4329],
        [0.9266, 0.9266]])

In [58]:
torch.ones_like(func(b[:,1])) @ torch.autograd.functional.jacobian(func,b[:,1])

tensor([0.3462, 0.4329, 0.9266])